[[terms_and_definitions]]
== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9],
which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards.
In particular:

* SHALL (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.
* SHOULD is the verb form used to indicate desirable ability or use, without mentioning or excluding other possibilities.
* MAY is the verb form used to indicate an action permissible within the limits of this specification.
* CAN is the verb form used for statements of possibility.

For the purposes of this document, the following additional terms and definitions apply.
Further discussion about _type_, _class_, _interface_, _property_, _attribute_ and _implementation_ terms
can be found in convention section (<<type_terminology>>).

[[term_API]]
application programming interface (API)::
a formally defined set of types and methods which establish a contract between client code which uses the API
and implementation code which provides the API

[[term_cardinality]]
cardinality::
number of elements in a set +
[small]#Note 1 to entry: Contrast with _multiplicity_, which is the range of possible cardinalities a set can hold.# +
 [source: ISO 19103]

[[term_conceptual_model]]
conceptual model::
model that defines concepts of a universe of discourse +
 [source: ISO 19101-1]

[[term_constraint]]
constraint::
UML condition or restriction expressed in natural language text or in a machine readable language
for the purpose of declaring some of the semantics of an element +
 [source: ISO 19103]

[[term_coordinate]]
coordinate::
one of a sequence of numbers designating the position of a point +
[small]#Note 1 to entry: In a spatial coordinate reference system, the coordinate numbers are qualified by units.# +
 [source: ISO 19111]

[[term_coordinate_operation]]
coordinate operation::
process using a mathematical model, based on a one-to-one relationship, that changes coordinates in a source coordinate
reference system to coordinates in a target coordinate reference system, or that changes coordinates at a source coordinate
epoch to coordinates at a target coordinate epoch within the same coordinate reference system +
 [source: ISO 19111]

[[term_crs]]
coordinate reference system::
coordinate system that is related to an object by a datum +
[small]#Note 1 to entry: Geodetic and vertical datums are referred to as reference frames.# +
[small]#Note 2 to entry: For geodetic and vertical reference frames, the object will be the Earth.
In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.# +
 [source: ISO 19111]

[[term_covariant]]
covariant type::
a type that can be replaced by a more specialized type when the property is overridden in a subclass +
[small]#Note 1 to entry: Some programming languages allow covariant return types in method declarations.# +

[[term_coverage]]
coverage::
feature that acts as a function to return values from its range for any direct position within its spatial,
temporal, or spatiotemporal domain +
 [source: ISO 19123]

[[term_dataset]]
dataset::
identifiable collection of data +
 [source: ISO 19115-1]

[[term_datatype]]
datatype::
specification of a value domain with operations allowed on values in this domain +
[small]#Examples: `Integer`, `Real`, `Boolean`, `String` and `Date`.# +
[small]#Note 1 to entry: Data types include primitive predefined types and user definable types.# +
 [source: ISO 19103]

[[term_dynamic_attribute]]
dynamic attribute::
characteristic of a feature in which its value varies with time +
 [source: OGC 16-140]

[[term_feature]]
feature::
abstraction of a real world phenomena +
[small]#Note 1 to entry: A feature can occur as a type or an instance.
Feature type or feature instance should be used when only one is meant.# +
 [source: ISO 19109]

[[term_feature_attribute]]
feature attribute::
characteristic of a feature +
[small]#Note 1 to entry: A feature attribute can occur as a type or an instance.
Feature attribute type or feature attribute instance is used when only one is meant.# +
 [source: ISO 19109]

[[term_feature_operation]]
feature operation::
operation that every instance of a feature type may perform +
 [source: ISO 19109]

[[term_function]]
function::
rule that associates each element from a domain (source, or domain of the function) to a unique element in another domain (target, co-domain, or range) +
 [source: ISO 19107:2003]

[[term_geographic_feature]]
geographic feature::
representation of real world phenomenon associated with a location relative to the Earth +
 [source: ISO 19101-2]

[[term_geometric_object]]
geometric object::
spatial object representing a geometric set +
 [source: ISO 19107:2003]

[[term_interface]]
interface::
UML classifier that represents a declaration of a set of coherent public UML features and obligations +
[small]#Note 1 to entry: An interface specifies a contract; any classifier that realizes the interface must fulfil that contract.
The obligations that can be associated with an interface are in the form of various kinds of constraints
(such as pre- and post-conditions) or protocol specifications,
which can impose ordering restrictions on interactions through the interface.# +
 [source: UML 2]

[[term_java]]
Java::
trademark of Oracle used to refer to an object oriented, single inheritance programming language
whose syntax derives from the C programming language and which is defined by the Java Language Specification

[[term_literal_value]]
literal value::
constant, explicitly specified value +
[small]#Note 1 to entry: This contrasts with a value that is determined by resolving a chain of substitution (e.g. a variable).# +
 [source: ISO 19143]

[[term_metadata]]
metadata::
data about data +
 [source: ISO 19115-1]

[[term_moving_feature]]
moving feature::
feature whose location changes over time +
[small]#Note 1 to entry: Its base representation uses a local origin and local coordinate vectors
of a geometric object at a given reference time.# +
[small]#Note 2 to entry: The local origin and ordinate vectors establish an engineering coordinate
reference system (ISO 19111), also called a local frame or a local Euclidean coordinate system.#

[[term_multiplicity]]
multiplicity::
UML specification of the range of allowable cardinalities that a set may assume +
[small]#Note 1 to entry: Contrast with _cardinality_, which is the number of elements in a set.# +
 [source: ISO 19103]

[[term_package]]
package::
UML general purpose mechanism for organizing elements into groups +
 [source: ISO 19103]

[[term_property]]
property::
facet or attribute of an object referenced by a name +
 [source: ISO 19143]

[[term_python]]
Python::
an interpreted high-level programming language for general-purpose programming +
 [source: Wikipedia]

[[term_realization]]
realization::
specialized abstraction relationship between two sets of model elements, one representing
a specification (the supplier) and the other representing an implementation of the latter (the client) +
[small]#Note 1 to entry: Realization indicates inheritance of behaviour without inheritance of structure.# +
[small]#Note 2 to entry: GeoAPI and GML are two realizations of OGC/ISO abstract specifications.# +
 [source: ISO 19103] (except note 2)

[[term_trajectory]]
trajectory::
path of a moving point described by a one parameter set of points +
 [source: ISO 19141]
