[[overview]]
== Geospatial API overview

The GeoAPI interfaces formalizes the handling of the types defined in the specification documents
for working with geographic information adopted by the International Organization for Standardization (ISO)
and the Open Geospatial Consortium (OGC).
Whereas the specifications define types, operations and relationships using the general UML notation,
the GeoAPI types implement those standards as programming language interfaces or simple classes.
The structure of the GeoAPI library mirrors the packaging and separation of the different ISO and OGC specifications
by grouping different types and functionality in separated {supported-languages} language packages.

.ISO specifications and GeoAPI packages mapping
image::packages.svg[]

The `opengis.annotation` package provides the annotation system
used to document the origin and obligation level of all methods and types in GeoAPI.
These annotations are available through introspection at runtime for any code which wishes to exploit this information.
The base of GeoAPI is formed by a formal mapping of the core types used by ISO and OGC standards to {supported-languages} equivalents,
along with extra types in the `opengis.util` package for types not provided in the standard libraries.
The packages in the `opengis.metadata` namespace cover the types defined in the ISO 19115 _Metadata_ specification,
which are data structures describing other structures.
The packages in the `opengis.parameter` and `opengis.referencing` namespaces
implement the types from the ISO 19111 _Spatial Referencing by Coordinates_ specification
complemented by the mathematical operator types from the OGC 01-009 _Coordinate Transformation Services_ implementation specification.
The packages in the `opengis.geometry` namespace cover the types defined in the ISO 19107 _Spatial Schema_ specification,
although in version 4.0 of the library only defines the elements from that specification needed by the geo-referencing types.
Finally the packages in the `opengis.feature` namespace
covers the meta-classes defined in the ISO 19109 _Rules for application schema_ specification,
completed by the dynamic attributes defined in OGC 14-083 _Moving Features_ specification.
This package is not needed for dynamic languages like Python.


include::informative/general.adoc[]

include::informative/core-types.adoc[]

include::informative/departures.adoc[]

include::informative/metadata/index.adoc[]
