[[terms-and-definitions]]
== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9],
which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards.
In particular:

* SHALL (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.
* SHOULD is the verb form used to indicate desirable ability or use, without mentioning or excluding other possibilities.
* MAY is the verb form used to indicate an action permissible within the limits of this specification.
* CAN is the verb form used for statements of possibility.

For the purposes of this document, the following additional terms and definitions apply.
Further discussion about _type_, _class_, _interface_, _property_, _attribute_ and _implementation_ terms
can be found in the <<type-terminology,conventions>> section.

[[term-API]]
[discrete]
=== Application Programming Interface (API)
a formally defined set of types and methods which establish a contract between client code which uses the API
and implementation code which provides the API

[[term-cardinality]]
[discrete]
=== cardinality
number of elements in a set +
[small]#Note 1 to entry: Contrast with _multiplicity_, which is the range of possible cardinalities a set can hold.# +
 [source: ISO 19103]

[[term-conceptual-model]]
[discrete]
=== conceptual model
model that defines concepts of a universe of discourse +
 [source: ISO 19101-1]

[[term-constraint]]
[discrete]
=== constraint
UML condition or restriction expressed in natural language text or in a machine readable language
for the purpose of declaring some of the semantics of an element +
 [source: ISO 19103]

[[term-coordinate]]
[discrete]
=== coordinate
one of a sequence of numbers designating the position of a point +
[small]#Note 1 to entry: In a spatial coordinate reference system, the coordinate numbers are qualified by units.# +
 [source: ISO 19111]

[[term-coordinate-operation]]
[discrete]
=== coordinate operation
process using a mathematical model, based on a one-to-one relationship, that changes coordinates in a source coordinate
reference system to coordinates in a target coordinate reference system, or that changes coordinates at a source coordinate
epoch to coordinates at a target coordinate epoch within the same coordinate reference system +
 [source: ISO 19111]

[[term-crs]]
[discrete]
=== coordinate reference system
coordinate system that is related to an object by a datum +
[small]#Note 1 to entry: Geodetic and vertical datums are referred to as reference frames.# +
[small]#Note 2 to entry: For geodetic and vertical reference frames, the object will be the Earth.
In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.# +
 [source: ISO 19111]

[[term-coverage]]
[discrete]
=== coverage
feature that acts as a function to return values from its range for any direct position within its spatial,
temporal, or spatiotemporal domain +
 [source: ISO 19123]

[[term-dataset]]
[discrete]
=== dataset
identifiable collection of data +
 [source: ISO 19115-1]

[[term-datatype]]
[discrete]
=== datatype
specification of a value domain with operations allowed on values in this domain +
[small]#Examples: `Integer`, `Real`, `Boolean`, `String` and `Date`.# +
[small]#Note 1 to entry: Data types include primitive predefined types and user definable types.# +
 [source: ISO 19103]

[[term-dynamic-attribute]]
[discrete]
=== dynamic attribute
characteristic of a feature in which its value varies with time +
 [source: OGC 16-140]

[[term-feature]]
[discrete]
=== feature
abstraction of a real world phenomena +
[small]#Note 1 to entry: A feature can occur as a type or an instance.
Feature type or feature instance should be used when only one is meant.# +
 [source: ISO 19109]

[[term-feature-attribute]]
[discrete]
=== feature attribute
characteristic of a feature +
[small]#Note 1 to entry: A feature attribute can occur as a type or an instance.
Feature attribute type or feature attribute instance is used when only one is meant.# +
 [source: ISO 19109]

[[term-feature-operation]]
[discrete]
=== feature operation
operation that every instance of a feature type may perform +
 [source: ISO 19109]

[[term-geographic-feature]]
[discrete]
=== geographic feature
representation of real world phenomenon associated with a location relative to the Earth +
 [source: ISO 19101-2]

[[term-geometric-object]]
[discrete]
=== geometric object
spatial object representing a geometric set +
 [source: ISO 19107:2003]

[[term-interface]]
[discrete]
=== interface
UML classifier that represents a declaration of a set of coherent public UML features and obligations +
[small]#Note 1 to entry: An interface specifies a contract; any classifier that realizes the interface must fulfil that contract.
The obligations that can be associated with an interface are in the form of various kinds of constraints
(such as pre- and post-conditions) or protocol specifications,
which can impose ordering restrictions on interactions through the interface.# +
 [source: UML 2]

[[term-java]]
[discrete]
=== Java
trademark of Oracle used to refer to an object oriented, single inheritance programming language
whose syntax derives from the C programming language and which is defined by the Java Language Specification

[[term-metadata]]
[discrete]
=== metadata
data about data +
 [source: ISO 19115-1]

[[term-moving-feature]]
[discrete]
=== moving feature
feature whose location changes over time +
[small]#Note 1 to entry: Its base representation uses a local origin and local coordinate vectors
of a geometric object at a given reference time.# +
[small]#Note 2 to entry: The local origin and ordinate vectors establish an engineering coordinate
reference system (ISO 19111), also called a local frame or a local Euclidean coordinate system.#

[[term-multiplicity]]
[discrete]
=== multiplicity
UML specification of the range of allowable cardinalities that a set may assume +
[small]#Note 1 to entry: Contrast with _cardinality_, which is the number of elements in a set.# +
 [source: ISO 19103]

[[term-package]]
[discrete]
=== package
UML general purpose mechanism for organizing elements into groups +
 [source: ISO 19103]

[[term-property]]
[discrete]
=== property
facet or attribute of an object referenced by a name +
 [source: ISO 19143]

[[term-python]]
[discrete]
=== Python
an interpreted high-level programming language for general-purpose programming +
 [source: Wikipedia]

[[term-realization]]
[discrete]
=== realization
specialized abstraction relationship between two sets of model elements, one representing
a specification (the supplier) and the other representing an implementation of the latter (the client) +
[small]#Note 1 to entry: Realization indicates inheritance of behaviour without inheritance of structure.# +
[small]#Note 2 to entry: GeoAPI and GML are two realizations of OGC/ISO abstract specifications.# +
 [source: ISO 19103] (except note 2)

[[term-trajectory]]
[discrete]
=== trajectory
path of a moving point described by a one parameter set of points +
 [source: ISO 19141]
