[#introduction]
== Introduction

GeoAPI contains a series of interfaces and classes in several packages which interpret into some programming languages
(currently {supported-languages}) the data model and UML types of the ISO and OGC standards documents.
The interfaces includes documentation which complement the injunctions of the ISO/OGC specifications by explaining
particularities of GeoAPI: interpretations made of the specifications where there was room for choice,
constraints specific to each programming language,
or standard patterns of behavior expected by the community of a programming language.
This document explains GeoAPI interfaces and defines its use by library code implementing the API and by client code calling the API.
Jointly with the interface definitions, this work aims to provide:

* a carefully considered interpretation of the OGC specifications for {supported-languages} languages,
* a base structure to facilitate the creation of software libraries which implement OGC standards,
* a well defined, full documented binding reducing the programming effort of using the OGC abstract model,
* and to facilitate the portability of application code between different implementations.

The interfaces defined in this standard provide one way to structure the use of the {supported-languages} languages
to implement softwares which follow the design and intents of the OGC/ISO specifications.
The creators of the GeoAPI interfaces consider this approach as an effective compromise between the OGC specifications,
the requirements of above-cited programming languages, and the tradition of the core libraries of those languages.

This version of the standard does not propose a complete set of interfaces covering the entire set of ISO/OGC abstract standards,
but focuses on an initial group of interfaces only.
This initial group of interfaces covers enough of the abstract model to permit the description of geospatial metadata,
the definition of coordinate reference systems and to enable operations on coordinate tuples between different reference systems.
The work writing interfaces matching other OGC specifications is done in the 'pending' version of the GeoAPI project.
It is expected that these other interfaces will be proposed for standardization in subsequent revisions of this specification
but the interfaces must first have been implemented, ideally several times, and then tested extensively by use.
