:Title:               OGC GeoAPI 3.1/4.0
:titletext:           OGC GeoAPI 3.1/4.0
:doctype:             book
:docinfo:             shared-head
:encoding:            utf-8
:lang:                en
:toc:                 left
:toclevels:           3
:numbered:
:sectids!:
:sectnums:
:sectanchors:
:xrefstyle:           short
:chapter-refsig:      section
:section-refsig:      §
:appendix-refsig:     annex
:stylesheet:          standard.css
:source-highlighter:  coderay
:supported-languages: Java and Python
:icons:               font
:imagesdir:           images
:attribute-missing:   warn
:appendix-caption:    Annex
:description: A set of types and methods which can be used for the manipulation of geographic \
information structured following the specifications adopted by the Technical Committee 211 of the \
International Organization for Standardization (ISO) and by the Open Geospatial Consortium (OGC).
:keywords: GeoAPI, programming, Java, Python, interface, geospatial, metadata, referencing, feature

= OGC GeoAPI 3.1/4.0

////
Comment for editors: AsciiDoctor syntax is described at https://asciidoctor.org/docs/user-manual.
No blank line shall appear in above header (a blank line marks the end of header).
Some constructs used in this document are:

    :foo:       Set an attribute value. Can be referenced in the document as {foo}.
    [foo]       Style to apply on a section (abstract, etc).
    [[foo]]     Anchor ID, defined manually for stability (automatic IDs are disabled by sectids!).
    == foo      Title of level 1. Use === for level 2, ==== for level 3, etc. up to level 5.
    .foo        Title associated to a paragraph, list, table or figure. Must be above the element.
    foo +       Line break (+ must be at the end of line).
    <<<         Page break.

Block (must start and end with the same sequence of characters):

    ----        Source code.
    ****        Aside text and content displayed outside the flow of the document.

Around words:

    *foo*       Format "foo" in bold characters.
    _foo_       Format "foo" in italic characters.
    `foo`       Format "foo" with monospaced font.
////

<<<
[cols = ">", frame = "none", grid = "none"]
|===================================================================================================
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <yyyy-mm-dd>
|Approval Date:   <yyyy-mm-dd>
|Publication Date:   <yyyy-mm-dd>
|External identifier of this OGC^®^ document: http://www.opengis.net/doc/is/geoapi/{m.n} [red yellow-background]#(TODO: put numbers)#
|Internal reference number of this OGC^®^ document:    YY-nnnrx
|Version: n.n
|Category: OGC^®^ Implementation Specification
|Editor:   Martin Desruisseaux
|===================================================================================================

[cols = "^", frame = "none"]
|==================
|[big]*{titletext}*
|==================

[cols = "^", frame = "none", grid = "none"]
|==============================================================================
|*Copyright notice*
|Copyright © 2009-2021 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|==============================================================================

[cols = "^", frame = "none"]
|=========
|*Warning*
|=========

This document is not an OGC Standard. This document is distributed for review and comment.
This document is subject to change without notice and may not be referred to as an OGC Standard.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights
of which they are aware and to provide supporting documentation.

[width = "50%", grid = "none"]
|=======================================
|Document type:   	OGC® Standard
|Document stage:   	Draft
|Document language: 	English
|=======================================

<<<
License Agreement

[small]#Permission is hereby granted by the Open Geospatial Consortium, ("Licensor"), free of charge and subject to the
terms set forth below, to any person obtaining a copy of this Intellectual Property and any associated documentation,
to deal in the Intellectual Property without restriction (except as set forth below), including without limitation the
rights to implement, use, copy, modify, merge, publish, distribute, and/or sublicense copies of the Intellectual Property,
and to permit persons to whom the Intellectual Property is furnished to do so, provided that all copyright notices on the
intellectual property are retained intact and that each person to whom the Intellectual Property is furnished agrees
to the terms of this Agreement.#

[small]#If you modify the Intellectual Property, all copies of the modified Intellectual Property must include,
in addition to the above copyright notice, a notice that the Intellectual Property includes modifications that
have not been approved or adopted by LICENSOR.#

[small]#THIS LICENSE IS A COPYRIGHT LICENSE ONLY, AND DOES NOT CONVEY ANY RIGHTS UNDER ANY PATENTS
THAT MAY BE IN FORCE ANYWHERE IN THE WORLD.#

[small]#THE INTELLECTUAL PROPERTY IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT OF THIRD PARTY RIGHTS.
THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE DO NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE INTELLECTUAL
PROPERTY WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE INTELLECTUAL PROPERTY WILL BE UNINTERRUPTED OR ERROR FREE.
ANY USE OF THE INTELLECTUAL PROPERTY SHALL BE MADE ENTIRELY AT THE USER’S OWN RISK. IN NO EVENT SHALL THE COPYRIGHT HOLDER
OR ANY CONTRIBUTOR OF INTELLECTUAL PROPERTY RIGHTS TO THE INTELLECTUAL PROPERTY BE LIABLE FOR ANY CLAIM, OR ANY DIRECT, SPECIAL,
INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM ANY ALLEGED INFRINGEMENT OR ANY LOSS OF USE, DATA
OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR UNDER ANY OTHER LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH
THE IMPLEMENTATION, USE, COMMERCIALIZATION OR PERFORMANCE OF THIS INTELLECTUAL PROPERTY.#

[small]#This license is effective until terminated. You may terminate it at any time by destroying the Intellectual Property
together with all copies in any form. The license will also terminate if you fail to comply with any term or condition of this
Agreement. Except as provided in the following sentence, no such termination of this license shall require the termination of
any third party end-user sublicense to the Intellectual Property which is in force as of the date of notice of such termination.
In addition, should the Intellectual Property, or the operation of the Intellectual Property, infringe, or in LICENSOR's sole
opinion be likely to infringe, any patent, copyright, trademark or other right of a third party, you agree that LICENSOR, in
its sole discretion, may terminate this license without any compensation or liability to you, your licensees or any other party.
You agree upon termination of any kind to destroy or cause to be destroyed the Intellectual Property together with all copies
in any form, whether held by you or by any third party.#

[small]#Except as contained in this notice, the name of LICENSOR or of any other holder of a copyright in all or part of
the Intellectual Property shall not be used in advertising or otherwise to promote the sale, use or other dealings in this
Intellectual Property without prior written authorization of LICENSOR or such copyright holder. LICENSOR is and shall at all
times be the sole entity that may authorize you or any third party to use certification marks, trademarks or other special
designations to indicate compliance with any LICENSOR standards or specifications.
This Agreement is governed by the laws of the Commonwealth of Massachusetts. The application to this Agreement
of the United Nations Convention on Contracts for the International Sale of Goods is hereby expressly excluded.
In the event any provision of this Agreement shall be deemed unenforceable, void or invalid, such provision shall be modified
so as to make it valid and enforceable, and as so modified the entire Agreement shall remain in full force and effect.
No decision, action or inaction by LICENSOR shall be construed to be a waiver of any rights or remedies available to it.#

<<<
toc::[]

<<<

include::clause_0_front_material.adoc[]

include::clause_1_scope.adoc[]

include::clause_2_conformance.adoc[]

include::clause_3_references.adoc[]

include::clause_4_terms_and_definitions.adoc[]

include::clause_5_conventions.adoc[]

include::clause_6_informative_text.adoc[]

include::clause_7_normative_text.adoc[]

<<<
include::annex-a_conformance_tests.adoc[]

<<<
include::annex-b_conformance_levels.adoc[]

<<<
include::annex-c_java_profile.adoc[]

<<<
include::annex-d_python_profile.adoc[]

<<<
include::annex-e_examples.adoc[]

<<<
include::annex-f_history.adoc[]

<<<
include::annex-g_bibliography.adoc[]
