[[collections]]
==== Collections
_From <<ISO19103>> §7.3.2.3_

GeoAPI implements multi-valued properties using the standard Collections Frameworks provided by {supported-languages}.
If the property has the `isUnique` meta-property, then the collection is a `Set`:
a finite collection of objects where each object appears only once in unspecified order.
If the property has the `isOrdered` meta-property, then the collection is a `Sequence`:
a collection of object where elements are ordered and may appear many times.

.Collections mapping
[options="header"]
|===============================================================
|Meta-property |ISO 19103:2015     |Java type       |Python type
|`isUnique`    |`Set`        ^(1)^ |`java.util.Set` |`Set`
|`isOrdered`   |`Sequence`   ^(1)^ |`java.util.List`|`Sequence`
|              |`Dictionary`       |`java.util.Map` |`dict`
|===============================================================

Notes:

* (1) Deprecated in ISO 19103:2024, but listed because still present in some standards.

Unless otherwise required by the semantic of a property, GeoAPI prefers to use the `Collection` type in Java method signatures.
This allows implementers to choose their preferred subtypes, usually `Set` or `List`.
The `Set` type is not the default type because enforcing element uniqueness may constrain implementations to use hash tables
or similar algorithms, which is not always practical.
