[[common_types]]
==== Common types
_From <<ISO19103>> §8.2_

Each core type of the OGC/ISO specifications maps to zero, one or two object structures in GeoAPI.
Where the mapping can be made directly to a programming language primitive type, such as `int` and `float`,
the language primitive is preferred. In languages where "primitives" and "wrappers" are distinct,
wrappers may be used instead of primitives on a case-by-case basis.
The following table shows the mapping used by GeoAPI to represent the primitive types in the ISO 19100 series.

.Primitive types mapping
[options="header"]
|================================================================================
|ISO 19103 interface    |Java type                              |Python type
|`Boolean`              |`boolean`                        ^(1)^ |`int`
|`Number`               |`java.lang.Number`                     |`int` or `float`
|`Integer`              |`int`                         ^(1)(2)^ |`int`
|`Real`                 |`double`                         ^(1)^ |`float`
|`Decimal` ^(3)^        |`java.math.BigDecimal`                 |`float`
|`Vector`               |unimplemented                          |unimplemented
|`CharacterString`      |`java.lang.String`               ^(4)^ |`str`
|`URI`                  |`java.net.URI`                         |
|`UUID`                 |`java.util.UUID`                       |
|================================================================================

Notes:

* (1) Wrapper types such as `java​.lang​.Integer` or `java​.util​.Optional­Int` may be used where appropriate.
* (2) Sometimes substituted by `long` or `java​.lang​.Long` where the value may exceed 2³².
* (3) `Decimal` differs from `Real`, as `Decimal` is exact in base 10 while `Real` may not.
* (4) Substituted by `org​.opengis​.util​.International­String` where the string representation depends on the locale.
