[[datetime]]
==== Date and time
_From <<ISO19103>> §7.2.2 to 7.2.4_

The ISO 19103 `Date` interface gives values for year, month and day
while the `Time` interface gives values for hour, minute and second.
`DateTime` is the combination of a date with a time, with or without timezone.
GeoAPI maps the ISO date and time interfaces to the types provided in the standard library of target languages.
However, this mapping is not a one-to-one relationship.
For example, the ISO `DateTime` interface can map to three different standard Java interfaces
(`LocalDateTime`, `ZonedDateTime` or `OffsetDateTime`)
depending on whether or not a timezone is present, and how the timezone is represented (by identifier or by offset).
The timezone information is often desired for geospatial data
(for example, in the acquisition time of a remote sensing image),
but may be undesired for some other cases like office opening hours
(for example, if they apply to all offices spanning the multiple timezones of a country).
GeoAPI generally uses a more flexible type than the one mandated by ISO specifications
for letting developers choose how they want to handle timezones.

.Date and time types suggested mapping
[options="header"]
|=========================================================================
|ISO 19103 interface   |Suggested Java class                  |Python type
|`Date`                |`java.time.LocalDate`     ^(1)^ ^(2)^ |
|`Time`                |`java.time.OffsetTime`    ^(1)^       |
|`DateTime`            |`java.time.ZonedDateTime` ^(1)^ ^(2)^ |`datetime`
|(none)                |`java.time.Instant`             ^(2)^ |
|=========================================================================

Notes:

* (1) The actual type mandated by GeoAPI is the more generic `java​.time.temporal.Temporal` interface.
* (2) Some properties defined in GeoAPI 3._x_ use the legacy `java​.util​.Date` class for historical reasons.

`DateTime` is distinct from `Instant`.
The former is expressed in the proleptic Gregorian calendar as described in <<ISO8601>>,
while the latter is an instantaneous point on the selected time scale, astronomical or atomic.
An `Instant` does not have year, month or day components.
It is instead a duration elapsed since an epoch,
and its conversion to a `Date­Time` may be complicated.
In GeoAPI, temporal objects in metadata are typically `Date­Time`
while coordinates in a temporal coordinate reference system are typically `Instant`.

The temporal objects defined by ISO 19103 are completed by more temporal objects defined by ISO 19108.
The latter are discussed in <<temporal>>, but follow the same principle of mapping to existing standards when possible.
