[[derived_properties]]
==== Derived methods

GeoAPI may define additional methods not explicitly specified in OGC/ISO abstract models,
when the values returned by those methods can be derived from the values provided by standard OGC/ISO properties.
Those extensions are enabled by the way properties are handled.
In OGC/ISO abstract models, each property may have its value stored verbatim,
for example as a column in a database table, an XML element in a file, or a field in a class.
For enabling efficient use of OGC/ISO models in relational databases or XML files,
the models are generally non-redundant: each value is stored in exactly one property.
By contrast in GeoAPI, all properties are getter methods:
no matter how implementations store property values, users can fetch them only through method calls.
Since methods are free to compute values from other properties,
GeoAPI uses this capability for making some information more easily accessible
in situations where property values can be reached only indirectly in OGC/ISO models.
Thee additional methods introduce apparent duplication,
but they should be thought of as links to the real properties, rather than copies of the property values.
Such methods are added sparsely,
in places where introducing them brings some harmonization by reducing the need for special cases.
Examples include: fetching the head of an arbitrary `Generic­Name`,
fetching the Geodetic Reference Frame indirectly associated to a `ProjectedCRS`,
fetching axes of an arbitrary Coordinate Reference System (including compound ones), and more.
The additional methods can be recognized by the absence of `@UML` annotation.
