[[generic_name]]
==== Name types
_From <<ISO19103>> §7.5_

A `Generic­Name` is a sequence of identifiers rooted within the context of a namespace.
`NameSpace` defines a domain in which names can be mapped to objects.
For example, names could be primary keys in a database table,
in which case the namespace is materialized by the table.
Each storage (XML, shapefiles, netCDF, …) may have their own constraints for names in their namespaces.

[[generic_name_UML]]
.Generic names derived from ISO 19103
image::names.svg[UML of name objects]

`GenericName` is the base interface for all names in a `NameSpace`.
A generic name can be either a `Local­Name`, or a `Scoped­Name` which is an aggregate of
a `Local­Name` (the _head_) for locating another `Name­Space` and
a `Generic­Name` (the _tail_) valid in that name space.
For example if `"urn:ogc:def:crs:EPSG:10:4326"` is a `Scoped­Name`,
then `"urn"` is the _head_ and `"ogc:def:crs:EPSG:10:4326"` is the _tail_.
GeoAPI extends the model by allowing navigation in the opposite direction,
with `"urn:ogc:def:crs:EPSG:10"` as the _path_ and `"4326"` as the _tip_.

[[path_components]]
.Components of a generic name
image::path_components.svg["urn:ogc:def:crs:EPSG:10" components]

`TypeName` and `MemberName` are subtypes of `LocalName`
for referencing a type (for example a class) and a member (for example a property in a class) respectively.
All those types are mapped to {supported-languages} classes as below:

.Name types mapping
[options="header"]
|=========================================================================================
|ISO 19103 interface |Java interface                 |Python class
|(constructors)      |`org.opengis.util.NameFactory` |
|`NameSpace`         |`org.opengis.util.NameSpace`   |`opengis.metadata.naming.NameSpace`
|`GenericName`       |`org.opengis.util.GenericName` |`opengis.metadata.naming.GenericName`
|`ScopedName`        |`org.opengis.util.ScopedName`  |`opengis.metadata.naming.ScopedName`
|`LocalName`         |`org.opengis.util.LocalName`   |`opengis.metadata.naming.LocalName`
|`TypeName`          |`org.opengis.util.TypeName`    |`opengis.metadata.naming.TypeName`
|`MemberName`        |`org.opengis.util.MemberName`  |`opengis.metadata.naming.MemberName`
|=========================================================================================


[[type_name_mapping]]
===== Mapping to programming languages
The https://schemas.opengis.net/definitions/1.1.0/data­Type.xml[data type URN standard value 1.1]
OGC schema derived from <<OGC07-092>> defines the following standard names (non-exhaustive list):

* `urn​:ogc​:def​:data­Type:OGC:1.1:boolean`
* `urn​:ogc​:def​:data­Type:OGC:1.1:nonNegative­Integer`
* `urn​:ogc​:def​:data­Type:OGC:1.1:string`
* `urn​:ogc​:def​:data­Type:OGC:1.1:anyURI`

Above names are valid values for `Type­Name`,
where `urn​:ogc​:def​:data­Type:OGC:1.1` is the scope of the `Local­Name`.
In addition, GeoAPI defines also the following type names using only `OGC` as the scope.
The general rule is to use the name used in UML diagrams of OGC/ISO standards.

.Standard type names and mapping to programming languages
[options="header"]
|===============================================================================
|Scoped type name      |Java class                                 |Python class
|`OGC:Boolean`         |`java.lang.Boolean`                        |`int`
|`OGC:Integer`         |`java.lang.Integer`                        |`int`
|`OGC:Real`            |`java.lang.Double`                         |`float`
|`OGC:Decimal`         |`java.math.BigDecimal`                     |`float`
|`OGC:CharacterString` |`java.lang.String`                         |`str`
|`OGC:FreeText`        |`org.opengis.util.InternationalString`     |`str`
|`OGC:PT_Locale`       |`java.util.Locale`                         |
|`OGC:DateTime`        |`java.time.ZonedDateTime`                  |
|`OGC:URI`             |`java.net.URI`                             |`str`
|`OGC:Matrix`          |`org.opengis.referencing.operation.Matrix` |`np.ndarray`
|`OGC:Coverage`        |`org.opengis.coverage.Coverage`            |`Coverage`
|`OGC:MD_Metadata`     |`org.opengis.metadata.Metadata`            |`Metadata`
|===============================================================================


[[generic_name_departures]]
===== Departures from ISO model

Generic names in GeoAPI differ from the OGC/ISO standards
as described in the following sub-sections.


[[generic_name_departures_for_generalization]]
====== Generalization
GeoAPI extends the ISO 19103 model by adding a (_path_, _tip_) pair in complement to the (_head_, _tail_) pair.
While the _head_ and _tip_ properties carry non-trivial information only inside `Scoped­Name`,
GeoAPI nevertheless makes them available from the parent `Generic­Name` interface (not shown in <<generic_name_UML>>)
with the restriction that they shall return `this` (Java) or `self` (Python) when the name is an instance of `Local­Name`.
This generalization makes common operations simpler without the need to check for the exact name interface.

[[generic_name_departures_as_renaming]]
====== Renaming
The ISO 19103 `Generic­Name.aName` property appears as `toString` in <<generic_name_UML>>,
but this property should be mapped to the standard mechanism for representing an arbitrary object
as a character string in the target programming language.
In Java this is the `toString()` method;
in Python this is `+__str__+` or `+__repr__+`.
This specification uses the Java method name as it is more readable, but other languages should adapt.
The `aName` and `scoped­Name` properties in sub-interfaces are replaced by inheritance of `toString` in above UML.

[[generic_name_omissions]]
====== Omissions
ISO 19103 defines mapping methods from a name to the object identified by that name:
`getObject()` in `GenericName` and numerous methods in `NameSpace`.
Those methods are not included in GeoAPI interfaces.
Instead, we left these mappings to other frameworks, for example _Java Naming and Directory Interface_ (JNDI).
An example in <<JNDI>> shows how some omitted methods can be implemented by JNDI in the Java language.

[[generic_name_additions]]
====== Additions
The `Name­Factory` is an extension to allow the construction of instances of these name types
(in GeoAPI, factories are realizations of constructors).
The `Generic­Name.toFully­Qualified­Name()` method is an addition for developer convenience.
All GeoAPI additions on name types carry no new information compared to ISO model.
