[[internationalization]]
==== Internationalization
_From <<ISO19103>> §C.2_

The `International­String` interface is defined by GeoAPI to handle textual sequences
which may potentially need to be translated for users of different locales.
Conceptually this acts as a `Character­String` but may, depending on the implementation,
provide access to locale-specific representations of that string.
GeoAPI `International­String` is closely related, but not identical, to ISO 19103 `Language­String`.
The main difference is that the latter is a character string in one specific language,
while `International­String` can be a collection of character strings in different locales.
This is useful, for example, when an implementation is operating on a server that serves multiple languages simultaneously,
to allow sending string representations in the locale of the client rather than the locale of the server running the GeoAPI implementation.

[[internationalization_UML]]
.Cultural and linguistic adaptability
image::localization.svg[UML of InternationalString]

The `toString()` method (`+__str__+` in Python) returns the text in a language of the implementer's choosing.
The `toString(Locale)` method tries to return the text in the specified language if available,
and otherwise falls back on a language of the implementer's choosing.
This specification makes no recommendation about the default or fallback languages,
because some programming languages provide their own mechanism
(e.g. using _Language Range_ as defined by <<RFC4647>>).
Consequently, GeoAPI delegates most internationalization types to the target language standard library, as shown in the following table.
An example in <<International­String>> shows the use of `International­String` in the Java language.

.Linguistic types mapping
[options="header"]
|==============================================================================
|ISO 19103 interface      |Java class or interface                |Python class
|`CharacterString`        |`java.lang.String`               ^(1)^ |`str`
|`LanguageString`         |`org.opengis.util.InternationalString` |`str`
|`LanguageCode`           |`java.util.Locale`                     |
|`Currency`         ^(2)^ |`java.util.Currency`                   |
|`CharacterSetCode` ^(3)^ |`java.nio.charset.Charset`             |
|==============================================================================

Notes:

* (1) Sometimes substituted by `Char­Sequence` or `International­String`.
* (2) Defined as a unit of measurement in ISO 19103 §C.4.24.
* (3) From ISO 19103 §7.2.10 (<<primitives,primitive types>>).


[[internationalization_departures]]
===== Departures from ISO model

Internationalization in GeoAPI differs from the OGC/ISO standards
as described in the following sub-sections.



[[internationalization_departures_as_renaming]]
====== Renaming
All GeoAPI linguistic types have names and properties different than the ISO 19103 types.
This is either because the ISO types are mapped to types provided by the target language standard library
or because the GeoAPI type is inspired by a similar effort in the target language ecosystem.

[[internationalization_departures_for_harmonization]]
====== Harmonization
`InternationalString` as defined by GeoAPI provides the same functionality as ISO 19115 `PT_FreeText`.
It can be applied to all ISO 19115 elements who's data type is `Character­String` and domain is “free text”.
Consequently, GeoAPI uses the single `International­String` interface for the two ISO types
`LanguageCode` (from ISO 19103) and `PT_FreeText` (from ISO 19115).
