[[parameters]]
==== Parameters
_From <<ISO19111>> §11.2, <<ISO19115-1>> §6.5.12, <<ISO19157>> §C.2.2.4_

The concept of operation parameters is defined in many OGC/ISO standards:

* <<ISO19111>> provides `CC​_Operation­Parameter`,
* <<ISO19115-1>> provides `SV​_Parameter`,
* <<ISO19157>> provides `DQM​_Parameter`,
* <<ISO19143>> provides `Argument`, and
* OGC 01-004 (a legacy standard, but still useful to GeoAPI) provided `GC​_Parameter­Info`.

GeoAPI provides a unified parameter framework in the `org​.opengis​.parameter` Java package.
The ISO 19111 model is adopted as the basis because it provides a clear separation between
the definition of a parameter (name, aliases, identifier, expected value type and units)
and the actual parameter value.
The parameter properties that are defined by other standards but not present
in `CC​_Operation­Parameter` are retrofitted in the GeoAPI parameter framework.

.Main parameter properties and their mapping to ISO standards
[options="header"]
|=====================================================================================================================
|GeoAPI             |ISO 19111       |ISO 19115       |ISO 19157     |ISO 19143 |Remarks
|`name`             |`name`          |`name`          |`name`        |`name`    |
|`alias`            |`alias`         |                |              |          |
|`identifier`       |`identifier`    |                |              |          |Optional, contrarily to `name` which is mandatory.
|`name.description` |                |                |`definition`  |          |Should be a short sentence.
|`description`      |                |`description`   |`description` |          |`BrowseGraphic` property not explicitly supported.
|`remarks`          |`remarks`       |                |              |          |
|`valueType`        |                |                |`valueType`   |`type`    |
|`direction`        |                |`direction`     |              |          |
|`minimumOccurs`    |`minimumOccurs` |`optionality`   |              |          |`optionality   = (minimumOccurs > 0)`
|`maximumOccurs`    |`maximumOccurs` |`repeatability` |              |          |`repeatability = (maximumOccurs > 1)`
|=====================================================================================================================

ISO 19157 `Description` type contains a mandatory text and an optional illustration.
Only the text description is explicitly stored in the GeoAPI unified parameter type.
However, if needed implementations can associate the `description` property to an
object that implement both the `International­String` and `Description` interfaces.



[[parameter_departures]]
===== Departures from ISO model

`OperationParameter` has been renamed as `ParameterDescriptor`
to emphasize that it only describes the parameters without providing values.
The `Descriptor` suffix is found in other Java libraries such as Java­Beans and Java Advanced Imaging.
