[[records]]
==== Record types
_From <<ISO19103>> §7.7_

Records define new data type as an heterogeneous aggregation of component data types (the fields).
A `Record­Type` defines dynamically constructed data type.
It is identified by a `Type­Name` and contains an arbitrary number of fields as (_name_, _type_) pairs.
A `Record` is an instance of `Record­Type` containing the actual field values.

.Records derived and extended from ISO 19103
image::records.svg[UML of record objects]

`Record` and `RecordType` are lookup mechanisms that associate field names to _values_ and _value types_ respectively.
Field names are locally mapped, and field types are most often primitives.
Because the `Record­Type` describes the structure of a set of records,
it is essentially a metaclass for that set of records viewed as a class.
In dynamic languages such as Python, the `Record` and `Record­Type` interfaces are not really needed
because those languages can handle dynamically constructed data types natively,
but they can nevertheless be useful as marker interfaces.

.Record types mapping
[options="header"]
|====================================================================================================
|ISO 19103 interface |Java class or interface                   |Python class
|`Any`               |`java.lang.Object`                        |
|`Type`              |`org.opengis.util.Type`                   |
|`Record`            |`org.opengis.util.Record`                 |`opengis.metadata.naming.Record`
|`RecordType`        |`org.opengis.util.RecordType`             |`opengis.metadata.naming.RecordType`
|`Field`             |`java.util.Map.Entry<MemberName, Type>`   |
|`FieldType`         |`java.util.Map.Entry<MemberName, Object>` |
|====================================================================================================

[[records_departures]]
===== Departures from ISO model

Records in GeoAPI differ from the OGC/ISO standards
as described in the following sub-sections.



[[records_additions]]
====== Additions
The `Type` interface and `type­Name` property were defined in the older ISO 19103:2005 standard
and are kept by GeoAPI despite their removal from ISO 19103:2015.
The `isInstance(…)` method is a GeoAPI extension.

[[records_omissions]]
====== Omissions
The ISO 19103 `Field` and `Field­Type` interfaces are omitted because the same functionality is achieved
with `Dictionary<Member­Name, Type>` and `Dictionary<Member­Name, Any>` respectively.
Dictionaries are realized by language-specific types such as `java​.util​.Map`
(see collection types in <<collections>>) which offer more flexibility.
In particular dictionaries provide functionality equivalent to the ISO 19103:2005 `locate(name : Member­Name)` method.
That method was defined in older ISO standard but removed in ISO 19103:2015 revision.
The use of dictionaries allows GeoAPI to keep the `locate` functionality despite the method removal.
