[[units]]
==== Units of measurement
_From <<ISO19103>> §8.2.14_

ISO 19103 represents measurements and their units by two base interfaces:
`Measure` for the result from performing the act of ascertaining the value of a characteristic of some entity,
and `UnitOf­Measure` as a quantity adopted as a standard of measurement for other quantities of the same kind.
These two base interfaces can be specialized with parallel sets of subtypes.
For example, `Length` could be defined as a `Measure` specialization for distances,
accompanied by `UomLength` as a `UnitOf­Measure` specialization for length units.
Likewise, `Area` could be defined together with `UomArea`, `Time` together with `UomTime`, _etc._

[NOTE]
======
ISO 19103:2015 §C.4 defined many subtypes such as `Area`, `UomArea`, _etc_.
ISO 19103:2024 defines only the base types.
The legacy subtypes are listed in <<uom-mapping>>.
======

GeoAPI does not define any interface for the ISO 19103 `Measure` and `UnitOf­Measure` types
because {supported-languages} already have their own library for units of measurement.
For example, Java has standardized a set of quantity interfaces in the Java Specification Request <<JSR385>>.
When such a language-specific standard exists and provides equivalent functionality to ISO 19103, that external standard is used.
See Java profile (<<uom_jsr>>) or Java example code (<<parameterized_units>>) for more information.
