[width="90%",cols="2,6"]
|===
|*Requirement 4* {set:cellbgcolor:#CACCCE}|/req/req-class-a/req-setters +
 +
{set:cellbgcolor:#FFFFFF}
"Setter" methods (methods which set the value of an object)
shall either succeed or throw an exception such as
`Unsupported­Operation­Exception` if the method is not implemented,
`Illegal­Argument­Exception` if the value is illegal in that implementation, or
`Illegal­State­Exception` if some context makes the use of that method illegal.
This list of exception types is not exclusive.
|===

.Example
[NOTE]
======
A call to `parameter.setValue(-10.25)` may have the first of following results which is applicable:

  * The method is supported and the -10.25 value is valid: +
    The setter method returns silently.
  * The method is not implemented by the library: +
    `Unsupported­Operation­Exception` is thrown.
  * Values for that parameter are restricted to positive numbers: +
    `Illegal­Argument­Exception` is thrown.
  * The `Parameter­Value` instance has been declared unmodifiable: +
    `Illegal­State­Exception` or `Unsupported­Operation­Exception` is thrown.
======
