[NOTE]
====
The ISO 19103 `Measure` type is represented by the `Quantity` interface in the Java API defined by JSR-363.
The Java standard defines various quantity subtypes in the same way than ISO 19103 does,
often with the same names (`Angle`, `Length`, `Area`, `Volume` and `Time`).
But contrarily to ISO 19103, JSR-363 does not define a parallel set of subtypes for units of measurement.
Instead, it defines only one unit type, `javax.measure.Unit<? extends Quantity>`, which is parametrized by the quantity type.
For example instead of defining a `UomLength` subtype,
developers use `Unit<Length>` to qualify the type of Unit or Measure being used.
Units of the same parametrized type can be used in unit conversions like below
(the `Units` class must be provided by a JSR-363 implementation):

[source,java]
----
Unit<Length> sourceUnit = Units.MILE;
Unit<Length> targetUnit = Units.KILOMETRE;
UnitConverter converter = source.getConverterTo(target);
double source = 123.2;
double target = converter.convert(source);
----

where the initial calls define units of length and then a converter is used to obtain the equivalent length in a new unit.
====
