[appendix,obligation="informative"]
[[history]]
== Revision History

This GeoAPI standard evolved from an effort at the Open Geospatial Consortium (OGC) and in the free software community
focused on developing a library of interfaces defining a coherent data model for the manipulation of geospatial data
based on the data model defined in the OGC Abstract Specifications.
GeoAPI interfaces originates with the publication in January 2001 of the implementation specification
<<OGC01-009>> _Coordinate Transformation Services_ Revision 1.00 (Martin Daly, ed.)
which included a set of interfaces written in different programming languages and in the `org​.opengis` namespace.
The GeoAPI project started in 2003 as an effort from several contributors to develop a set of Java language interfaces
which could be shared between several projects.
The GeoAPI project subsequently considered the interfaces of OGC 01-009 as version 0.1 of GeoAPI
and started working on GeoAPI 1.0 in collaboration with developers writing the OGC specification _Geographic Objects_.
Subsequently, the Open Geospatial Consortium jettisoned its own Abstract Specifications and adopted,
as the basis for further work, the standards developed by the Technical Committee 211 of the
International Organization for Standardization (ISO) in its ISO 19100 series.
The GeoAPI project therefore realigned its interfaces with those standards.
In 2003, version 1.0 of GeoAPI interfaces was released to match the release of the first public draft
of the implementation specification <<OGC03-064>> _GO-1 Application Objects_ Version 1.0 (Greg Reynolds, ed.).
The standardization effort of GO-1 took a couple of years during which extensive work was made on GeoAPI interfaces.
Release 2.0 of GeoAPI was made at the time of the final publication of the GO-1 specification in 2005.
GO-1 has been retired later, but a new working group has been formed in 2009 for continuing GeoAPI development
with a more restricted scope: to provide interfaces for existing OGC standards only, without defining new conceptual models.
GeoAPI 3.0.0 has been released in 2011, GeoAPI 3.0.1 in 2017, and GeoAPI 3.0.2 in 2023.

[options="header,unnumbered"]
|===============================================================================================
|Date       |Release        |Editor              |Clauses modified         |Description
|2009-04-08 |3.0.0-draft    |Adrian Custer       |All                      |Initial public draft
|2010-02-11 |3.0.0          |Martin Desruisseaux |§6.2, 6.4, annexes       |Clarifications & departures
|2016-11-07 |3.0.1          |Martin Desruisseaux |§3, 6.2.9, annex D       |Replaced JSR-275 by JSR-363
|2022-12-26 |3.0.2          |Martin Desruisseaux |§3, 6.2.9, annex D       |Replaced JSR-363 by JSR-385
|2023-XX-XX |3.1 / 4.0      |Martin Desruisseaux |All                      |Rewrite
|===============================================================================================

[[future_work]]
=== Future work

This version of the standard does not propose a complete set of interfaces covering the entire set of OGC/ISO abstract standards,
but focuses on an initial group of interfaces only.
This initial group of interfaces covers enough of the abstract model to permit the description of geospatial metadata,
reference systems, features, and to enable operations on coordinate tuples.
The work writing interfaces matching other OGC specifications is done in the “pending” directory of the GeoAPI project.
It is expected that these other interfaces will be proposed for standardization in subsequent revisions of this specification
but the interfaces must first have been implemented, ideally several times, and then tested extensively by use.
