[[conventions]]
== Conventions
This section provides details for conventions used in the document.
All examples in this document are informative only.


[[UML_notation]]
=== UML notation

Unified Modeling Language (UML) static structure diagrams appearing in this document
are used as described in Subclause 5.2 of OGC Web Services Common <<OGC06-121>>.


[[type_terminology]]
=== Type terminology

The meaning of _type_, _class_, _interface_, _property_ and _attribute_ can vary depending on the programming language.
This document follows the <<term_interface,UML 2 definition of interface>> as a declaration of a set of coherent public
operations, properties and obligations specifying a contract.
UML interfaces are represented in programming languages by Java interfaces and Python abstract classes.
The word _class_ is generally not used in this document except in discussions specific to a programming language,
in which case the word takes the meaning defined by the target language;
in Java this is often (but not only) an implementation of an interface.

The word _type_ is used as a generic term for _interface_, _class_ (whatever it is in target programming languages),
_code list_, _enumeration_ or the description of a <<term_feature,feature>>.
Note that code lists, enumerations and feature types are not interfaces.

The word _property_ (not attribute) is used for values or associations defined by an interface.
This document reserves the word _attribute_ for <<term_feature_attribute,feature attributes>> or XML attributes.

The meaning of _implementation_ depends on the context.
From the perspective of OGC/ISO abstract specifications,
Java interfaces or Python abstract classes are implementations of the abstract models,
in the same way as XML Schema Definitions (XSD) are other implementations of the same abstract models.
But from the perspective of programming languages, interfaces are not implementations;
instead the word "implementation" is used for concrete classes.
In this document, the types provided by GeoAPI are said to be an implementation of abstract models,
while the concrete classes provided by vendors are said to be an implementations of GeoAPI.


[[abbreviations]]
=== Abbreviated terms

The following symbols and abbreviated terms are used in this specification:

API::  Application Program Interface
BBOX:: Bounding Box
CRS::  Coordinate Reference System
CS::   Coordinate System
GML::  Geographic Markup Language
ISO::  International Organization for Standardization
JDBC:: Java Database Connectivity
JNDI:: Java Naming and Directory Interface
ODBC:: Open Database Connectivity
OGC::  Open Geospatial Consortium
UML::  Unified Modeling Language
URI::  Uniform Resource Identifiers
UTC::  Coordinated Universal Time
UUID:: Universally Unique Identifier
WKT::  Well Known Text
WMS::  Web Map Service
XML::  Extensible Markup Language
XSD::  XML Schema Definition
1D::   One Dimensional
2D::   Two Dimensional
3D::   Three Dimensional
nD::   Multi-Dimensional
λ::    Geodetic longitude
φ::    Geodetic latitude


[[identifiers]]
=== Identifiers
The normative provisions in this specification are denoted by the URI:

http://www.opengis.net/spec/geoapi/{edition}/

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.


[[package_namespaces]]
==== Package namespaces

This specification uses `"opengis"` in the text for denoting a package or module in OGC namespace,
but the fully qualified name depends on the programming language.
For example, the metadata package is spelled `"org.opengis.metadata"` in Java
but only `"opengis.metadata"` (without `"org"` prefix) in Python.
Except in language-specific notes, this specification uses the shorter form in the text
and lets readers adapt to their programming language of interest.
