[[conformance]]
== Conformance

This standard defines interfaces in {supported-languages} programming languages.
The normative publication of the interfaces occurs in the ASCII or binary format specific to each target language.
The interfaces are distributed in ZIP bundles along with the API documentation.
An online version of the API documentation, which may contain fixes for errata discovered after publication of this specification,
is available at the URLs listed below:

.Distribution formats
[options="header", cols="1,3,3"]
|========================================================================================================
|                |Java                                    |Python
|Interfaces:     |Java Archive (JAR) binary               |Python source files (.py)
|Documentation:  |Javadoc as HTML files                   |MkDocs generated pages as HTML files
|Online version: |http://www.geoapi.org/snapshot/javadoc/ |http://www.geoapi.org/snapshot/python/
|========================================================================================================

#TODO: The `snapshot` elements in above URLs will be replaced by `3.1` and `4.0` after release.#

Unlike other OGC/ISO standards, the UML diagrams in this specification are purely informative.
The reason is because the diagrams show only a small subset of all interfaces and properties provided by GeoAPI,
and details such as naming conventions (<<naming>>) differ in their materialization in {supported-languages} languages.
The complete and normative UML diagrams are provided by the abstract specifications listed in <<references>>.

This specification defines several conformance classes
for implementations covering different packages of the API or providing different levels of complexity in their implementations.
GeoAPI provides a test suite through which to establish conformance of GeoAPI implementations.
Requirements for 2 standardization target types are considered:

* *Libraries* which provide software components for building geospatial applications.
* *Applications* which use the above-cited software components.

The second target type (applications) leaves more freedom than the first target type (libraries).
In particular, applications are free to delete any types, methods or functionalities that they do not use.
Requirements for the two target types are given in <<requirements>>.

Conformance with this standard shall be checked using all the relevant tests specified in <<conformance_tests>> of this document.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the
OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.
In order to conform to this OGC® interface standard, a software implementation shall choose to implement:

* Any one of the conformance levels specified in <<conformance_tests>>.
* Any one of the Distributed Computing Platform profiles specified in <<java>> through <<python>> (normative).
