/*
 *    GeoAPI - Java interfaces for OGC/ISO standards
 *    Copyright © 2009-2023 Open Geospatial Consortium, Inc.
 *    http://www.geoapi.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Javadoc taglets and annotation processing tools for processing GeoAPI after compilation.
 * Those tools are used mostly for javadoc generation.
 * Some services offered by this module are:
 *
 * <ul class="verbose">
 *   <li><b>Generating API index page:</b>
 *     A summary of all types and members can be generated by the
 *     {@link org.opengis.tools.apt.IndexGenerator} processor.</li>
 *   <li><b>Documenting a summary of API changes:</b>
 *     A summary of API changes can be generated by the
 *     {@link org.opengis.tools.version.ChangeReport} class.</li>
 * </ul>
 *
 * Usage instructions from command-line are in the
 * <a href="https://github.com/opengeospatial/geoapi/tree/master/tools">README.md</a> file.
 *
 * @author  Martin Desruisseaux (Geomatys)
 * @version 4.0
 * @since   3.0
 */
module org.opengis.geoapi.build {
    requires jdk.javadoc;
}
