[[annotations]]
==== Annotated API

The `opengis.annotation` package allows GeoAPI to document the UML elements
from the various specification documents used for defining the {supported-languages} constructs.
Those annotations encode the source document, stereotype, original name, and obligation level
of the various types, properties and operations published by GeoAPI.
The source document may be completed by a version number when the GeoAPI construct
is based on a different edition of a normative document than the dated references
listed in the <<references,references clause>>.
GeoAPI defines two annotations in the Java language (no annotation in Python):
`@UML` which is applied on types and properties (fields or methods), and
`@Classifier` which can be applied only on types.
Those annotations are shown in the figure below:

.Annotations reflecting UML elements used by GeoAPI
image::annotations.svg[UML of GeoAPI annotations]

Those annotations are related to the ISO 19115-1 Metadata standard in the following way:
above `Obligation` enumeration is the `MD_ObligationCode` enumeration defined by ISO 19115,
moved into the `opengis.annotation` package for making it closer to other UML-related types.
A `forbidden` value has been added for handling the cases where a property defined in a parent
interface is inapplicable to a sub-interface
(those cases are declared in ISO standards with the maximum number of occurrence set to zero).
Above `Stereotype` enumeration is a copy of the `MD_DatatypeCode` code list defined by ISO 19115,
retaining only the values relevant to GeoAPI.
This duplication exists because the ISO 19115 standard defines a code list, while Java annotations require enumerations.

++++
<details>
<summary>Annotations in Java source code</summary>
++++
include::../code/java/annotation.adoc[]
++++
</details>
++++
