[[annotations]]
=== Annotated API

The `opengis.annotation` package provides annotations which reflect UML elements
from the various specification documents used for defining GeoAPI.
Those annotations enable GeoAPI to document the source document, stereotype, original name,
and obligation level of the various types, properties and operations.
GeoAPI defines two annotations in the Java language (no annotation in Python):
`@UML` which can be applied on types and properties (fields or methods), and
`@Classifier` which can be applied only on types.
Those annotations are shown in the figure below:

.Annotations reflecting UML elements used by GeoAPI
image::annotations.svg[]

Above `Obligation` enumeration is the `MD_ObligationCode` enumeration defined by the ISO 19115-1 standard,
moved in the `opengis.annotation` package for making it closer to other UML-related types and
with a `forbidden` value added for handling the cases where the maximum number of occurrence is zero.
Such case happen when a property defined in a parent type is inapplicable to a sub-type.

Above `Stereotype` enumeration is a copy the `MD_DatatypeCode` code list defined by ISO 19115-1,
retaining only the values relevant to GeoAPI.
This duplication exists because the ISO 19115 standard defines a code lists, while Java annotations require enumerations.


.Annotations in Java source code
****
All classes, interfaces or enumeration types in GeoAPI which are based on a published standard
shall have an `@UML` annotation documenting the standard in which are defined the type or method,
the original name of the element and the obligation level if other than mandatory.
As an example, the annotation label for the `ProjectedCRS` interface appears in the source code as:

[source,java]
----
@UML(identifier = "SC_ProjectedCRS",
     specification = ISO_19111)
public interface ProjectedCRS extends GeneralDerivedCRS {
    ...
}
----

which specifies that the type was defined in ISO 19111 standard,
in the `SC` "Coordinate Reference System" package as the type `SC_ProjectedCRS`.
In addition, that interface contains the method `getCoordinateSystem()` with the following annotation:

[source,java]
----
@UML(identifier    = "coordinateSystem",
     obligation    = MANDATORY,
     specification = ISO_19111)
CartesianCS getCoordinateSystem();
----

which indicates that the method was defined in the same ISO 19111 specification
but had the name `coordinateSystem` in the standard rather than the `getCoordinateSystem` name used by GeoAPI,
and that a non-null value must be provided by every `ProjectedCRS` instance.
****

<<UML-introspection,An example in annex>> shows how these annotations are available at runtime by introspection.
