[[annotations]]
==== Annotated API

The `opengis.annotation` package allows GeoAPI to document the UML elements
from the various specification documents used for defining the {supported-languages} constructs.
Those annotations encode the source document, stereotype, original name, and obligation level
of the various types, properties and operations published by GeoAPI.
The source document may be completed by a version number when the GeoAPI construct
is based on a different edition of a normative document than the dated references
listed in <<references>>.
GeoAPI defines two annotations in the Java language (no annotation in Python):
`@UML` which is applied on types and properties (fields or methods), and
`@Classifier` which can be applied only on types.
Those annotations are shown in the figure below:

.Annotations reflecting UML elements used by GeoAPI
image::annotations.svg[UML of GeoAPI annotations]

[NOTE]
========================================
Those annotations are related to the ISO 19115-1 Metadata standard in the following way:
the GeoAPI `Obligation` is the ISO `MD_ObligationCode` enumeration
moved into the annotation package for use with other UML-related types.
A `forbidden` enumeration value has been added for handling the cases where a property defined in a parent
interface is inapplicable to a sub-interface ([0…0] multiplicity in abstract models).
The GeoAPI `Stereotype` enumeration is a copy of the ISO `MD_DatatypeCode` code list
retaining only the values relevant to annotation of GeoAPI programming elements.
This duplication exists because the ISO 19115 standard defines a code list, while Java annotations require enumerations.
========================================

An example in <<UML-introspection>> shows how these annotations are applied in the Java language
and how they are available at runtime by introspection.
