[[collections]]
==== Collections
[.reference]_From ISO 19103:2015 §7.3_

GeoAPI implements ISO 19103 collection interfaces using the standard Collections Frameworks provided by {supported-languages}.
A `Set` is a finite collection of objects where each object appears only once.
A `Bag` is similar to a `Set` except that it may contain duplicated instances.
The order of elements in a `Set` or a `Bag` is not specified.
A `Sequence` is similar to a `Bag` except that elements are ordered.

.Collections mapping
[.compact, options="header"]
|========================================================
|ISO 19103 interface |Java type              |Python type
|`Collection`        |`java.util.Collection` |`Sequence`
|`Bag`               |`java.util.Collection` |
|`Set`               |`java.util.Set`        |
|`Sequence`          |`java.util.List`       |`Sequence`
|`Dictionary`        |`java.util.Map`        |
|========================================================

Unless otherwise required by the semantic of a property, GeoAPI preferably uses the `Collection` type in Java method signatures.
This allows implementers to choose their preferred subtypes, usually `Set` or `Sequence`.
The `Set` type is not the default type because enforcing element uniqueness may constraint implementations to use hash tables
or similar algorithms, which is not always practical.
