[[controlled-vocabulary]]
==== Controlled vocabulary
[.reference]_From ISO 19103:2015 §6.5_

The <<bibliography,feature models abstract specification>> defines controlled vocabulary as an
established list of standardized terminology (names, words or phrases) with associated definitions
for use to identify, describe, index or retrieve information.
A controlled vocabulary implementation commonly found in many programming languages is enumeration.

GeoAPI distinguishes two different types of controlled vocabularies:
enumerations are _closed_ controlled vocabularies:
it is not possible to add new members (except by releasing new GeoAPI versions).
By contrast, code lists are _open_ vocabularies:
they provide a basic set of members defined at compile-time,
but users are free to add new members at runtime.
Many programming languages provide an `enum` construct for the closed case.
For the opened case, GeoAPI defines the `CodeList` abstract class in Java.

.Enumerated types mapping
[.compact, options="header"]
|========================================================
|ISO 19103 type |Java type                   |Python type
|CodeList       |`org.opengis.util.CodeList` |`Enum` ^(1)^
|Enumeration    |`java.lang.Enum`            |`Enum`
|`Bit`          |unimplemented               |
|`Digit`        |unimplemented               |
|`Sign`         |unimplemented               |
|========================================================

[small]#(1) GeoAPI does not yet provide an extensible implementation of code list in the Python language,
but this limitation may be addressed in a future version.# +

Code lists can be extended by calls to `valueOf(String)` methods in the Java language.
Extensions should follow ISO 19103 recommendation:
_Extensions of a code list use the existing code list values and merely add additional unique values.
These additional values should not replace an existing code by changing the name or definition,
or have the same definition as an existing value._

The figure below shows one closed (on the left side) and one opened (on the right side) enumeration derived from ISO 19115.
The `ControlledVocabulary` parent interface is a GeoAPI addition. Its indirect inheritance by `PixelOrientation` is because
the `Enum` class is defined by programming language standard library and can not be modified directly.
<<CodeList-introspection,An example in annex>> shows how code lists are used in the Java language.

.Closed and opened enumeration examples
image::enumeration-examples.svg[Enumeration and CodeList examples]


===== Departures from ISO model

====== Harmonization
GeoAPI introduces a `ControlledVocabulary` interface as the parent type of enumerations and code lists.
It provides methods for accessing properties common to both enumerated types:
the name used in the target programming language (e.g. `"UPPER_LEFT"`),
the identifier used in OGC/ISO specification (e.g. `"upperLeft"`),
and its position (ordinal) in the enumeration.
Note that the ordinal values may change in any future specification if new enumeration values are added,
but this is not necessarily a problem because not all algorithms need stable values (e.g. hash tables).

====== Renaming
In some specifications (for example ISO 19115), code list and enumeration names end with the `Code` suffix.
Some other specifications (for example ISO 19111) do not use any particular suffix.
The mapping to programmatic API may uniformize those type names to a single convention, depending on the target language.
For the Java API, `Code` suffixes are omitted in class names.
For the Python API, class names are left unchanged.
See <<naming,Naming conventions>> for examples.
