[[controlled-vocabulary]]
==== Controlled vocabulary
[.reference]_From ISO 19103:2015 §6.5_

GeoAPI distinguishes between two enumerated types depending on whether the complete set of literal types is known
when the code is originally created, or if the list may be extended at run time.
Many language provides an `enum` construct for the former case and
GeoAPI defines the `CodeList` abstract class in Java for the later case.

.Enumerated types mapping
[.compact, options="header"]
|========================================================
|ISO 19103 type |Java type                   |Python type
|CodeList       |`org.opengis.util.CodeList` |
|Enumeration    |`java.lang.Enum`            |`Enum`
|`Bit`          |unimplemented               |
|`Digit`        |unimplemented               |
|`Sign`         |unimplemented               |
|========================================================

In some specifications (for example ISO 19115), code list and enumeration names end with the `Code` suffix.
Some other specifications (for example ISO 19111) do not use any particular suffix.
The mapping to programmatic API may uniformize those type names to a single convention, depending on the target language.
For the Java API, `Code` suffixes are omitted in class names.
For the Python API, class names are left unchanged.

++++
<details>
<summary>Code lists in Java</summary>
++++
include::../code/java/code-list.adoc[]
++++
</details>
++++
