[[controlled-vocabulary]]
==== Controlled vocabulary
[.reference]_From ISO 19103:2015 §6.5_

The <<bibliography,feature models abstract specification>> defines controlled vocabulary as an
established list of standardized terminology (names, words or phrases) with associated definitions
for use to identify, describe, index or retrieve information.
A simple implementation of controlled vocabulary commonly found in programming languages is enumeration.

GeoAPI distinguishes two different types of controlled vocabularies:
enumerations are _closed_ controlled vocabularies:
it is not possible to add new members (except by releasing new GeoAPI versions).
By contrast, code lists are _open_ vocabularies:
they provide a basic set of members defined at compile-time,
but users are free to add new members at runtime.

Closed vocabularies are modeled as Enumeration elements within UML models.
Many languages provide an `enum` construct for the closed case and
GeoAPI defines the `CodeList` abstract class in Java for the open case.

.Enumerated types mapping
[.compact, options="header"]
|========================================================
|ISO 19103 type |Java type                   |Python type
|CodeList       |`org.opengis.util.CodeList` |`Enum`
|Enumeration    |`java.lang.Enum`            |`Enum`
|`Bit`          |unimplemented               |
|`Digit`        |unimplemented               |
|`Sign`         |unimplemented               |
|========================================================

In some specifications (for example ISO 19115), code list and enumeration names end with the `Code` suffix.
Some other specifications (for example ISO 19111) do not use any particular suffix.
The mapping to programmatic API may uniformize those type names to a single convention, depending on the target language.
For the Java API, `Code` suffixes are omitted in class names.
For the Python API, class names are left unchanged.
See <<naming,Naming conventions>> for examples.

<<CodeList-introspection,An example in annex>> shows how code list are used in the Java language.
