[[derived-properties]]
==== Derived methods

GeoAPI may define additional methods not explicitly specified in OGC/ISO abstract models,
when the values returned by those methods can be derived from the values provided by standard OGC/ISO properties.
Those extensions are enabled by a GeoAPI restriction in the way properties are handled.
In OGC/ISO abstract models each property could have its value stored verbatim,
for example as a column in a database table, an XML element in a file or a field in a class.
For enabling efficient use of OGS/ISO models in relational databases or XML files,
those models are generally non-redundant: each value is stored in exactly one property.
By contrast in GeoAPI all properties are getter methods;
no matter how implementations store property values, users can fetch them only through method calls.
Since methods are free to compute values from other properties,
GeoAPI uses this capability for making some information more easily accessible
in situations where property values can be reached only indirectly in OGC/ISO models.
Those additional methods introduce apparent duplications,
but they should be thought as links to the real properties rather than copies of the property values.
Those methods are added sparsely,
in places where introducing them brings some harmonization by reducing the needs to perform special cases.
Examples include fetching the head of an arbitrary `GenericName`,
fetching the Geodetic Reference Frame indirectly associated to a `ProjectedCRS`,
fetching axes of an arbitrary Coordinate Reference System (including compound ones), and more.
Those additional methods can be recognized by the absence of `@UML` annotation.
