[[generic_name]]
==== Name types
[.reference]_From ISO 19103:2015 §7.5_

A `GenericName` is a sequence of identifiers rooted within the context of a namespace.
`NameSpace` defines a domain in which names can be mapped to objects.
For example, names could be primary keys in a database table,
in which case the namespace is materialized by the table.
Each storage (XML, shapefiles, netCDF, …) may have their own constraints for names in their namespaces.

.Generic names derived from ISO 19103
image::names.svg[UML of name objects]

`GenericName` is the base interface for all names in a `NameSpace`.
A generic name can be either a `LocalName`, or a `ScopedName` which is an aggregate of
a `LocalName` (the _head_) for locating another `NameSpace` and
a `GenericName` (the _tail_) valid in that name space.
For example if `"urn:​ogc:​def:​crs:​EPSG:​10:​4326"` is a `ScopedName`,
then `"urn"` is the _head_ and `"ogc:​def:​crs:​EPSG:​10:​4326"` is the _tail_.
GeoAPI extends the model by allowing navigation in the opposite direction,
with `"urn:​ogc:​def:​crs:​EPSG:​10"` as the _path_ and `"4326"` as the _tip_.

.Components of a generic name
image::path_components.svg["urn:​ogc:​def:​crs:​EPSG:​10" components]

`TypeName` and `MemberName` are subtypes of `LocalName`
for referencing a type (for example a class) and a member (for example a property in a class) respectively.
All those types are mapped to {supported-languages} classes as below:

.Name types mapping
[.compact, options="header"]
|=========================================================================================
|ISO 19103 interface |Java interface                 |Python class
|(constructors)      |`org.opengis.util.NameFactory` |
|`NameSpace`         |`org.opengis.util.NameSpace`   |`opengis.metadata.naming.NameSpace`
|`GenericName`       |`org.opengis.util.GenericName` |`opengis.metadata.naming.GenericName`
|`ScopedName`        |`org.opengis.util.ScopedName`  |`opengis.metadata.naming.ScopedName`
|`LocalName`         |`org.opengis.util.LocalName`   |`opengis.metadata.naming.LocalName`
|`TypeName`          |`org.opengis.util.TypeName`    |`opengis.metadata.naming.TypeName`
|`MemberName`        |`org.opengis.util.MemberName`  |`opengis.metadata.naming.MemberName`
|=========================================================================================


[[type_name_mapping]]
===== Mapping to programming languages
The [data type URN standard value 1.1](https://schemas.opengis.net/definitions/1.1.0/dataType.xml) OGC schema
defines the following standard names (non-exhaustive list):

* `urn:ogc:def:dataType:OGC:1.1:boolean`
* `urn:ogc:def:dataType:OGC:1.1:nonNegativeInteger`
* `urn:ogc:def:dataType:OGC:1.1:string`
* `urn:ogc:def:dataType:OGC:1.1:anyURI`

Above names are valid values for `TypeName`,
where `urn:ogc:def:dataType:OGC:1.1` is the scope of the `LocalName`.
In addition, GeoAPI defines also the following type names using only `OGC` as the scope.
The general rule is to use the name used in UML diagrams of OGC/ISO standards.

.Standard type names and mapping to programming languages
[.compact, options="header"]
|===============================================================================
|Scoped type name      |Java class                                 |Python class
|`OGC:Boolean`         |`java.lang.Boolean`                        |#TODO#
|`OGC:Integer`         |`java.lang.Integer`                        |#TODO#
|`OGC:Real`            |`java.lang.Double`                         |#TODO#
|`OGC:Decimal`         |`java.math.BigDecimal`                     |#TODO#
|`OGC:CharacterString` |`java.lang.String`                         |#TODO#
|`OGC:FreeText`        |`org.opengis.util.InternationalString`     |#TODO#
|`OGC:PT_Locale`       |`java.util.Locale`                         |#TODO#
|`OGC:DateTime`        |`java.time.ZonedDateTime`                  |#TODO#
|`OGC:URI`             |`java.net.URI`                             |#TODO#
|`OGC:Matrix`          |`org.opengis.referencing.operation.Matrix` |#TODO#
|`OGC:Coverage`        |`org.opengis.coverage.Coverage`            |#TODO#
|`OGC:MD_Metadata`     |`org.opengis.metadata.Metadata`            |#TODO#
|===============================================================================


[[generic_name_departures]]
===== Departures from ISO model

====== Generalization
GeoAPI extends the ISO 19103 model by adding a (_path_, _tip_) pair in complement to the (_head_, _tail_) pair.
While the _head_ and _tip_ properties carry non-trivial information only inside `ScopedName`,
GeoAPI nevertheless makes them available from the parent `GenericName` interface (not shown in above UML diagram)
with the restriction that they shall return `this` (Java) or `self` (Python) when the name is an instance of `LocalName`.
This generalization makes common operations simpler without the need to check for the exact name interface.

====== Renaming
The ISO 19103 `GenericName.aName` property appears as `toString` in above UML diagram,
but this property should be mapped to the standard mechanism for representing an arbitrary object
as a character string in the target programming language.
In Java this is the `toString()` method;
in Python this is `+__str__+` or `+__repr__+`.
This specification uses the Java method name as it is more readable, but other languages should adapt.
The `aName` and `scopedName` properties in sub-interfaces are replaced by inheritance of `toString` in above UML.

====== Omissions
ISO 19103 defines mapping methods from a name to the object identified by that name:
`getObject()` in `GenericName` and numerous methods in `NameSpace`.
Those methods are not included in GeoAPI interfaces.
Instead, we left these mappings to other frameworks, for example _Java Naming and Directory Interface_ (JNDI).
An example in <<JNDI>> shows how some omitted methods can be implemented by JNDI in the Java language.

====== Additions
The `NameFactory` is an extension to allow the construction of instances of these name types
(in GeoAPI, factories are realizations of constructors).
The `GenericName.toFullyQualifiedName()` method is an addition for developer convenience.
All GeoAPI additions on name types carry no new information compared to ISO model.
