[[internationalization]]
=== Internationalization
[.reference]_From ISO 19103:2015 §C.2_

The `InternationalString` type is defined by GeoAPI to handle textual sequences
which may potentially need to be translated for users of different locales.
Conceptually this act as a `CharacterString` but may, depending on the implementation,
provide access to locale specific representations of that string.
GeoAPI `InternationalString` is closely related, but not identical, to ISO 19103 `LanguageString`.
The main difference is that the later is a character string in one specific language,
while `InternationalString` can be a collection of character strings in different locales.
This is useful, for example, when an implementation is operating on a server that serves multiple languages simultaneously,
to allow sending string representations in the locale of the client rather than the locale of the server running the GeoAPI implementation.

[small]#Note: `InternationalString` is inspired by JSR-150 (Internationalization Service for J2EE) with support for different timezones omitted.#

.Linguistic types mapping
[.compact, options="header"]
|==========================================================================
|ISO 19103 type        |Java type                              |Python type
|`CharacterString`     |`java.lang.String`                     |`str`
|`LanguageString`      |`org.opengis.util.InternationalString` |
|`LanguageCode`        |`java.util.Locale`                     |
|==========================================================================

.Internationalization in Java
****
The `org.opengis.util.InternationalString` interface provides a container for multiple versions of the same text,
each for a specific `java.util.Locale` — the identifier used in Java for a specific language, possibly in a named territory.

[source,java]
----
NameFactory factory =  ...                      // Implementation dependent.
InternationalString multiLingual = factory.createInternationalString(Map.of(
        Locale.ENGLISH, "My documents",
        Locale.FRENCH,  "Mes documents"));

System.out.println(localized);         // Language at implementation choice.
System.out.println(localized.toString(Locale.FRENCH));
----

The method to obtain factories is not specified by this standard and therefore depends on the design of the library implementation.
Also, the locale used by default depends on the choice of the implementation so the result of the call `toString()`
without parameters will depend on the implementation.
****
