[[multiplicity]]
==== Multiplicity conventions

The UML diagrams may specify arbitrary multiplicities (minimum and maximum number of occurrences) for each property.
But GeoAPI recognizes only the following four multiplicities,
materialized in the API <<annotations,as annotations>> and in the method signatures.
If a different multiplicity is needed, then [0 … ∞] should be used
with a restriction documented in the text attached to the property.

* *[0 … 0]* — the property can not be set (this happen sometime in subtypes).
* *[0 … 1]* — the property is optional or conditional.
* *[1 … 1]* — the property is mandatory.
* *[0 … ∞]* — the property can appear an arbitrary number of times, including zero or one.

Some programming languages have an `Optional` construct for differentiating the [0 … 1] and [1 … 1] cases.
This construct is used where appropriate, but shall be considered only as a hint.
It may appear in a mandatory property if that property was optional in the parent interface.
Conversely, absence of `Optional` construct is not a guarantee that the value will never be null.
Some properties fall in gray area, where they are _usually_ not null but may be null in some rare situations.
For example the `ellipsoid` property of a Geodetic Reference Frame is mandatory when used in the context of
geographic or projected coordinate reference systems, which are by far the most common cases.
Even when used in other contexts, the ellipsoid is optional but still recommended.
Consequently GeoAPI does not use the `Optional` construct for the `ellipsoid` property
in order to keep the most common usages simpler, but robust applications should be prepared to handle a null value.
Developers should refer to the API documentation for the policy on null values.
