[[records]]
==== Record types
[.reference]_From ISO 19103:2015 §7.7_

Records define new data type as an heterogeneous aggregation of component data types (the fields).
A `RecordType` defines dynamically constructed data type.
It is identified by a `TypeName` and contains an arbitrary number of fields as (_name_, _type_) pairs.
A `Record` is an instance of `RecordType` containing the actual field values.

.Records derived and extended from ISO 19103
image::records.svg[UML of record objects]

`Record` and `RecordType` are lookup mechanisms that associate field names to _values_ and _value types_ respectively.
Field names are locally mapped, and field types are most often primitives.
Because the `RecordType` describes the structure of a set of records,
it is essentially a metaclass for that set of records viewed as a class.
In dynamic languages such as Python, the `Record` and `RecordType` interfaces are not really needed
because those languages can handle dynamically constructed data types natively,
but they can nevertheless be useful as marker interfaces.

.Record types mapping
[.compact, options="header"]
|==========================================================================================
|ISO 19103 interface |Java class or interface         |Python class
|`Any`               |`java.lang.Object`              |
|`Type`              |`org.opengis.util.Type`         |
|`Record`            |`org.opengis.util.Record`       |`opengis.metadata.naming.Record`
|`RecordType`        |`org.opengis.util.RecordType`   |`opengis.metadata.naming.RecordType`
|`Field`             |`Map.Entry<MemberName, Type>`   |
|`FieldType`         |`Map.Entry<MemberName, Object>` |
|==========================================================================================
[small]#`Map.Entry` in above table means `java.util.Map.Entry`.# +

===== Departures from ISO model

====== Additions
The `Type` interface and `typeName` property were defined in the older ISO 19103:2005 standard
and are kept by GeoAPI despite their removal from ISO 19103:2015.
The `isInstance(…)` method is a GeoAPI extension.

====== Omissions
The ISO 19103 `Field` and `FieldType` interfaces are omitted because the same functionality is achieved
with `Dictionary<MemberName, Type>` and `Dictionary<MemberName, Any>` respectively.
Dictionaries are realized by language-specific types such as `java.util.Map`
(see collection types in <<collections>>) which offer more flexibility.
In particular dictionaries provide functionality equivalent to the ISO 19103:2005 `locate(name : MemberName)` method.
That method was defined in older ISO standard but removed in ISO 19103:2015 revision.
The use of dictionaries allows GeoAPI to keep the `locate` functionality despite the method removal.
