[[uom]]
=== Units of measurement
[.reference]_From ISO 19103:2015 §C.4_

Measurements and their units are represented by two base classes defined in ISO 19103:
`Measure` for the result from performing the act of ascertaining the value of a characteristic of some entity,
and `UnitOfMeasure` as a quantity adopted as a standard of measurement for other quantities of the same kind.
Those two base classes have a parallel set of subtypes:
`Length` (a `Measure` specialization for distances) is accompanied by `UomLength`
(a `UnitOfMeasure` specialization for length units),
`Area` is accompanied with `UomArea`, _etc._

Some languages have a standard library for units of measurement.
For example Java has standardized a set of quantity types in the JSR-363 standard.
When such language-specific standard exists and provides equivalent functionality to ISO 19103, that external standard is used.
Otherwise new types are defined following ISO 19103 definitions of units of measurement.

.Units of measurement mapping
[.compact, options="header"]
|=========================================================================
|ISO 19103 Type       |Java Type                              |Python type
|`Measure`            |`javax.measure.Quantity`               |
|`DirectedMeasure`    |Unimplemented                          |
|`UnitOfMeasure`      |`javax.measure.Unit<?>`                |
|`Area`               |`javax.measure.quantity.Area`          |
|`UomArea`            |`javax.measure.Unit<Area>`             |
|`Length`             |`javax.measure.quantity.Length`        |
|`Distance`           |`javax.measure.quantity.Length`        |
|`UomLength`          |`javax.measure.Unit<Length>`           |
|`Angle`              |`javax.measure.quantity.Angle`         |
|`UomAngle`           |`javax.measure.Unit<Angle>`            |
|`Scale`              |`javax.measure.quantity.Dimensionless` |
|`UomScale`           |`javax.measure.Unit<Dimensionless>`    |
|`Time`               |`javax.measure.quantity.Time`          |
|`UomTime`            |`javax.measure.Unit<Time>`             |
|`Volume`             |`javax.measure.quantity.Volume`        |
|`UomVolume`          |`javax.measure.Unit<Volume>`           |
|`Velocity`           |`javax.measure.quantity.Speed`         |
|`UomVelocity`        |`javax.measure.Unit<Speed>`            |
|`AngularVelocity`    |Unimplemented                          |
|`UomAngularVelocity` |Unimplemented                          |
|=========================================================================

.Parameterized units in Java
****
The ISO 19103 `Measure` type is represented by the `Quantity` interface in the Java API defined by JSR-363.
The Java standard defines various quantity subtypes in the same way than ISO 19103 does,
often with the same names (`Angle`, `Length`, `Area`, `Volume` and `Time`).
But contrarily to ISO 19103, JSR-363 does not define a parallel set of subtypes for units of measurement.
Instead, it defines only one unit type, `javax.measure.Unit<? extends Quantity>`, which is parametrized by the quantity type.
For example instead of defining a `UomLength` subtype,
developers use `Unit<Length>` to qualify the type of Unit or Measure being used.
Units of the same parametrized type can be used in unit conversions like below
(the `Units` class must be provided by a JSR-363 implementation):

[source,java]
----
Unit<Length> sourceUnit = Units.MILE;
Unit<Length> targetUnit = Units.KILOMETRE;
UnitConverter converter = source.getConverterTo(target);
double source = 123.2;
double target = converter.convert(source);
----

where the initial calls define units of length and then a converter is used to obtain the equivalent length in a new unit.
****
