[[referencing_departures]]
==== Departures from ISO 19111

===== Elements from legacy OGC 01-009
A major extension of GeoAPI compared the ISO 19111 standard comes from the inclusion,
directly in the `Coordinate­Operation` interface,
of a method providing access to the `Math­Transform` interface from the older OGC 01-009 specification.
That interface performs the actual computation of coordinates in target CRS from the coordinates in source CRS.
This separation between a type providing metadata about coordinate operation and a type doing the actual work
existed in OGC 01-009 and has been kept by GeoAPI for giving to developers more flexibility regarding optimizations.
The operations really executed by `Math­Transform` can be very different than the operations described by `Coordinate­Operation`
as long as they are mathematically equivalent.

Since the 2019 revision of ISO 19111 specification, the `Coordinate­Operation` interface has a `transform(…)` method.
But that new method can be implemented as a convenience method redirecting the work to `Math­Transform`.

===== Coordinate system association
In the ISO 19111 specification, only `SingleCRS` has an association to `coordinateSystem`.
GeoAPI moves this association to the `Coordinate­Reference­System` parent interface for user convenience,
because coordinate system (CS) dimension and axes are frequently requested information
and will always be available, directly or indirectly, even for `CompoundCRS`.
However only coordinate systems associated to `SingleCRS` can be instances of ISO 19111 concrete subtypes
(`CartesianCS`, `SphericalCS`, `VerticalCS`, _etc._);
it is not possible to assign a standard concrete type to the coordinate system of a `CompoundCRS`.
For the later case, users see only the abstract `CoordinateSystem` type which serves merely as an axis container.
The concrete CS subtype can be hidden in implementation details.

.Rational
[NOTE]
======
This generalization would not be appropriate for a database schema or for formats such as _Well Known Text_
because axes listed with a `CompoundCRS` would be redundant with axes listed with each CRS component.
But this consideration does not apply to programming languages: the axes do not need to be repeated
because each method such as `CoordinateSystem.getAxis(int)` contains code, not necessarily data structure.
Implementations can redirect requests for `CoordinateSystem` axes to corresponding `CompoundCRS` elements.
======

===== Type and property names
The ISO 19111 `CRS` type name has been expanded to the `Coordinate­Reference­System` name in GeoAPI
for compatibility with previous GeoAPI versions.
It is also common practice in Java language to avoid abbreviations.

In the `General­Derived­CRS` interface, the `conversion` association to `Conversion`
has been renamed `conversion­From­Base` for making clear that the source CRS is the `baseCRS`.
This naming is similar to the one used in OGC 01-009 with direction reversed.
