[[math_transform]]
==== Math transforms
[.reference]_From OGC 01-009 §12.4.5_

The `Coordinate­Operation` object introduced in previous section provides high-level information
(source and target CRS, domain of validity, positional accuracy, operation parameter values, _etc_).
The actual mathematical work is performed by a separated object obtained by a call to `get­MathTransform()`.
At the difference of `Coordinate­Operation` instances, `Math­Transform` instances do not carry any metadata.
They are kind of black box which know nothing about the source and target CRS, the domain or the accuracy
(actually the same `Math­Transform` can be used for different pairs of CRS if the mathematical work is the same),
Furthermore, `Math­Transform` may be implemented in a very different way than what `Coordinate­Operation` said.
In particular many conceptually different coordinate operations such as unit conversions, axis swapping, _etc._
can be implemented by `Math­Transform` as affine transforms and concatenated for efficiency.
The result may be a `MathTransform` doing in a single step a calculation
described by `Coordinate­Operation` as a chain of distinct operations.
Having `MathTransform` separated from `CoordinateOperation` gives more flexibility to implementers for optimizations.

.Association between Coordinate Operation and Math Transform
image::math_transform.svg["urn:​ogc:​def:​crs:​EPSG:​10" Partial UML of MathTransform]

`MathTransform` has a method taking a `DirectPosition` (the coordinates in source CRS) in input
and returning a `DirectPosition` (the coordinates in target CRS) in output.
But `MathTransform` provides also various methods operating on an arbitrary number of coordinate tuples
packed in arrays of `float` or `double` types. If there is many points to transform,
the methods operating on arrays will generally be much more efficient than the method operating on `DirectPosition`.
The example in <<java_coordinate_operation>> shows how to transform in Java the coordinates of 6 cities.


===== Partial derivatives
[.reference]_From OGC 01-009 §12.4.5.6_

`MathTransform` can also provide the derivative of the transform function at a point.
The derivative is the matrix of the non-translating portion of the approximate affine map at the point.
For example, if _P_ is a map projection converting degrees of latitude and longitude (_φ_, _λ_)
into projected coordinates (_x_, _y_) in metres,
then the derivative _P′_ can be represented by a Jacobian matrix as below:

++++++++++
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" alttext="MathML capable browser required">
  <msup><mi>P</mi><mo>′</mo></msup><mo>(</mo><mi>φ</mi><mo>,</mo><mi>λ</mi><mo>)</mo>
  <mo>=</mo>
  <mrow>
    <mo>[</mo>
    <mrow>
      <mtable>
        <mtr>
          <mtd><mfrac><mrow><mo>∂</mo><mi>x</mi></mrow><mrow><mo>∂</mo><mi>φ</mi></mrow></mfrac></mtd>
          <mtd><mfrac><mrow><mo>∂</mo><mi>x</mi></mrow><mrow><mo>∂</mo><mi>λ</mi></mrow></mfrac></mtd>
        </mtr>
        <mtr>
          <mtd><mfrac><mrow><mo>∂</mo><mi>y</mi></mrow><mrow><mo>∂</mo><mi>φ</mi></mrow></mfrac></mtd>
          <mtd><mfrac><mrow><mo>∂</mo><mi>y</mi></mrow><mrow><mo>∂</mo><mi>λ</mi></mrow></mfrac></mtd>
        </mtr>
      </mtable>
    </mrow>
    <mo>]</mo>
  </mrow>
</math>
++++++++++
