[[coordinate-operation]]
==== Coordinate operation
[.reference]_From ISO 19111:2019 §12 and §C.5_

A Coordinate Operation can _transform_ or _convert_ coordinate tuples from one Coordinate Reference System (CRS) to another CRS.
There is four kinds of coordinate operations in GeoAPI:

* A _coordinate conversion_ is the implementation of some mathematical formulas without empirically derived parameters.
  Conversions can be as accurate as floating point computations allow.
  Map projections are kinds of coordinate conversions.
* A _coordinate transformation_ involves empirically derived parameters.
  Because those parameters have observational error
  and because the transformation method is only an estimation of a complex reality,
  the result of applying a coordinate transformation contain errors
  with a magnitude estimated by the `coordinate­Operation­Accuracy` property.
  Several different transformation may exist for the same pair of coordinate reference systems,
  differing in their method, parameter values and accuracy characteristics.
* [red yellow-background]#TODO: Point motion operation.#
* A _concatenated operation_ is a sequential execution of any of above operations.

GeoAPI provides three ways to create a coordinate operation:

===== From a pair of CRS
Given a source coordinate reference system (CRS) in which existing coordinate values are expressed,
and a target coordinate reference system in which coordinate values are desired,
`Coordinate­Operation­Factory` can provide a coordinate operation performing the conversion or transformation work.
An <<CoordinateOperation-java,example in Java>> is provided in annex.

===== From an authority code
Above method leaves some flexibility to implementations for choosing a coordinate operation when several possibilities exist.
If a specific operation is needed and if that operation is identified by an authority code,
it can be provided by `Coordinate­Operation­Authority­Factory`.

===== From a parameter values
The `Parameter­Value` interface provides methods to set the value of the parameter.
In the general use pattern for these types, a `Parameter­Value­Group` containing all the named parameters
for an operation method is first obtained from the `Operation­Method` or the `Math­Transform­Factory`,
and then each `Parameter­Value` instance is obtained in turn and its value set.
This use pattern ensures that all the needed parameters for an operation method can be obtained as a single block.
An example is given in annex for the <<ProjectedCRS-java,Java>> language.
