[[filter]]
==== Filter
[.reference]_From ISO 19143:2010 §7.[7…11]_

A filter is a predicate that identifies a subset of resources from a collection of resources.
Each resource instance is evaluated against a filter, which always evaluates to `true` or `false`.
If the filter evaluates to `true`, the resource instance is included in the result set.
If the filter evaluates to `false`, the resource instance is ignored.
Roughly speaking, a filter encodes the information present in the `WHERE` clause of a SQL statement.

There are various sub-interfaces of this interface that represent many types of filters,
such as simple property comparisons or spatial queries.
The following diagram shows the 4 basic types of filters
together with the code lists identifying which operation is applied.
More specialized sub-types such as `Binary­Comparison­Operator` and `Distance­Operator` are not shown in this diagram.

.Partial UML of filters
image::filter.svg[Filter UML]

In above diagram, the `operatorType` property defined in the `Filter` parent interface
is overridden by more specialized types (shown as associations) in each sub-interface.
This is <<term_covariant,type covariance>>.
Likewise `expression` is defined in parent interface with unconstrained multiplicity,
but that multiplicity is restrained in sub-interfaces.

Filter operands are expressions.
For example, a filter named "Property­Is­Equal­To" uses two expressions.
The first expression may be a `Value­Reference` fetching the value of a property
and the second expression may be a `Literal` with the desired value.
