[[coordinate_operation]]
==== Coordinate operations
_From <<ISO19111>> §12 and §C.5_

A Coordinate Operation can _transform_ or _convert_ coordinate tuples from one Coordinate Reference System (CRS) to another CRS.
There are four kinds of coordinate operations in GeoAPI:

* A _coordinate conversion_ is the implementation of some mathematical formulas without empirically derived parameters.
  Conversions can be as accurate as floating point computations allow.
  Map projections are kinds of coordinate conversions.
* A _coordinate transformation_ involves empirically derived parameters.
  Because those parameters have observational error
  and because transformation methods are only approximations of a complex reality,
  the coordinate transformation results also have errors.
  Furthermore, several transformations may exist for the same pair of coordinate reference systems,
  differing in their method, parameter values, domain of validity and accuracy characteristics.
* #TODO: Point motion operation.#
* A _concatenated operation_ defines a sequential execution of any of above operations.

GeoAPI provides three ways to create a coordinate operation,
described in the following sub-sections.

[[coordinate_operation_from_crs_pair]]
===== From a pair of CRS
Given a source coordinate reference system (CRS) in which existing coordinate values are expressed,
and a target coordinate reference system in which coordinate values are desired,
`CoordinateOperationFactory` can provide a coordinate operation performing the conversion or transformation work.
An example is given in <<java_coordinate_operation>> for the Java language.

Note that when several possibilities exist for the same pair of CRS,
the selected transformation is implementation-dependent.
Implementations should select the "best" transformation based on criterion
such as accuracy and domain of validity, but GeoAPI does not specify any rule.
Users are encouraged to verify which transformation has been selected by invoking
the `Coordinate­Operation.toWKT()` method.

#TODO: `RegisterOperations` returns a set of all operations.#

[[coordinate_operation_from_authority_code]]
===== From an authority code
If a determinist operation is required and if that operation is identified by an authority code,
then that operation can be obtained with `Coordinate­Operation­Authority­Factory`.
This approach avoids the implementation-dependent variability of the approach described in previous paragraph.

[[coordinate_operation_from_parameters]]
===== From operation parameter values
The `Parameter­Value` interface provides methods to set the value of the operation parameter.
In the general use pattern for these types, a `Parameter­Value­Group` containing all the named parameters
for an operation method is first obtained from the `Operation­Method` or the `Math­Transform­Factory`,
and then each `Parameter­Value` instance is obtained in turn and its value set.
This use pattern ensures that all the needed parameters for an operation method can be obtained as a single block.
An example is given in <<java_create_crs>> for the Java language.
