[[coordinate_system]]
==== Coordinate systems
_From <<ISO19111>> §10 and §C.3_

A Coordinate System (CS) contains the set of axes that spans a given coordinate space.
Each axis defines an approximate direction (north, south, east, west, up, down, port, starboard, past, future, _etc._),
units of measurement, minimal and maximal values, and what happen after reaching those extremum.
For example, in longitude case, after +180° the coordinate values continue at −180°.

In addition to axis definitions, another important coordinate system characteristic is their type (`CartesianCS`, `SphericalCS`, _etc._).
The CS type implies the set of mathematical rules for calculating geometric quantities such as angles, distances and surfaces.
Usually the various CS subtypes do not define any new programmatic methods compared to the parent type, but are nevertheless important for type safety.
For example, many calculations or associations are legal only when all axes are perpendicular to each other.
In such case the coordinate system type is restricted to `CartesianCS` in method signatures.

[[cs_crs_associations]]
===== Associations with CRS
The coordinate system associated to a `SingleCRS` shall be an instance of one `Coordinate­System` subtype.
It should be a subtype defined by ISO 19111 when possible, or a user-defined subtype when no standard type describes the space geometry.
The standard coordinate system types are Cartesian, affine, spherical, cylindrical, polar, ellipsoidal, vertical, temporal, ordinal and parametric.

The coordinate system associated to a `CompoundCRS` is of unspecified type.
None of the standard types describe the full space geometry, and implementers do not need to define a public type.
The `Coordinate­System` in this context is only a list of axes defined as the concatenation of the list of axes of all components,
without saying anything about space geometry.
Requesting elements in that list can be thought as redirection to the coordinate system of a CRS component.

.Example
[NOTE]
======
An implementation may know that the third coordinate system axis of a `CompoundCRS`
is the first axis of the second CRS component, and redirects axis information requests to that component.
In this scenario the `Coordinate­System` implementations does the work that users would need to do themselves
if they wanted information about axes, but in a more convenient and potentially more efficient way.
======

Since above paragraphs define coordinate system for both `SingleCRS` and `CompoundCRS` interfaces,
GeoAPI provides the `coordinate­System` association in the `Coordinate­Reference­System` (CRS) parent interface.
It makes easy for users to get information about the coordinate system axes of any CRS,
with automatic redirection to `CompoundCRS` components when needed.
