[[referencing_wkt]]
==== Well-Known Text (WKT)
_From <<ISO19162>> and <<OGC01-009>> §7.1_

Most objects in the `opengis.referencing` packages can be imported and exported in _Well-Known Text_ (WKT) format.
This format allows the exchange of CRS definitions with implementations of other OGC standards such as web services.
GeoAPI provides two `toWKT()` methods for producing a WKT representation of an object:

* One method is defined in the `Identified­Object` parent interface and is inherited notably by `Coordinate­Reference­System`.
  But that method can also be used with `Coordinate­Operation` and various components such as `Datum`.
  Well Known Text (WKT) character strings produced by that method shall be compliant with the format defined
  in the <<ISO19162>> standard.
* A second `toWKT()` method is defined in the `Math­Transform` interface, which is not an object defined by ISO standards.
  Character strings produced by that method shall be compliant with the format defined in <<OGC01-009>> §7.1.
  Other sections such as OGC 01-009 §7.2 should be ignored since they are replaced by ISO 19162.

Difference between the two WKT representations is illustrated below.
For a very simple operation doing only a swapping of latitude and longitude axes,
the ISO 19162 representation of the `Coordinate­Operation` object can be as below:

++++++++++
<div class="listingblock">
<pre>COORDINATEOPERATION["Axis order change (2D)",
  SOURCECRS[GEODCRS["RGF93", <span class="wkt-omitted">...definition omitted for brevity...</span>, ID["EPSG", 4171]]],
  TARGETCRS[GEODCRS["RGF93 (lon-lat)", <span class="wkt-omitted">...definition omitted for brevity...</span>, ID["EPSG", 7084]]],
  METHOD["Axis Order Reversal (2D)", ID["EPSG", 9843]],
  AREA["World."], BBOX[-90.00, -180.00, 90.00, 180.00]]</pre>
</div>
++++++++++

The <<OGC01-009>> §7.1 representation of the `Math­Transform` associated to above coordinate operation can be as below.
All metadata information (source and target CRS, domain of validity, _etc._) are lost, and the human-readable
_"Axis Order Reversal"_ operation is replaced by a more mathematical _"Affine parametric transformation"_ operation.

[source]
--------------------------------------------
PARAM_MT["Affine",
  PARAMETER["num_row", 3],
  PARAMETER["num_col", 3],
  PARAMETER["elt_0_0", 0.0],
  PARAMETER["elt_0_1", 1.0],
  PARAMETER["elt_1_0", 1.0],
  PARAMETER["elt_1_1", 0.0]]
--------------------------------------------

Those two representations are complementary.
`Coordinate­Operation.toWKT()` provides high-level information about the operation
together with metadata for understanding the context.
`Math­Transform.toWKT()` said more information about how the operation is implemented,
which is useful for analyzing the validity of transformation results.

The converse operation – creating an object from a WKT definition – is done by `create­FromWKT(…)` methods
defined in `CRSFactory` and `Math­Transform­Factory` interface.
