[[metadata-departures]]
==== Departures from ISO 19115

A departure in the GeoAPI metadata packages from the published ISO 19115 standard is in the way GeoAPI metadata package
added the types and methods defined in the specification ISO 19115-2 – _Extensions for imagery and gridded data_.
The latter was forced to create a number of types to hold elements which naturally could occur directly in the types
defined by ISO 19115. We integrated such types directly into the existing types rather than adding complexity to the API
which exists by historical accident.
For example ISO 19115-2 defines a `MI_Band` type which extends the `MD_Band` type defined by ISO 19115-1,
with the addition of a `transferFunctionType` property (among others) for completing the `scaleFactor` and
`offset` properties defined by ISO 19115-1. GeoAPI merges those two classes together,
with <<annotations,annotations>> on each property for declaring the originating standard.
The metadata classes merged in such way are:

.Metadata ISO 19115-2 classes merged with ISO 19115-1 parent classes
[.compact, options="header"]
|=================================================================
|ISO 19115-1 parent class |ISO 19115-2 subclass merged with parent
|`LI_ProcessStep`         |`LE_ProcessStep`
|`LI_Source`              |`LE_Source`
|`MD_Band`                |`MI_Band`
|`MD_CoverageDescription` |`MI_CoverageDescription`
|`MD_Georectified`        |`MI_Georectified`
|`MD_Georeferenceable`    |`MI_Georeferenceable`
|`MD_ImageDescription`    |`MI_ImageDescription`
|`MD_Metadata`            |`MI_Metadata`
|=================================================================


Another departure come from GeoAPI replacing the `MD_ReferenceSystem` class by `RS_ReferenceSystem`.
Coordinate Reference Systems (CRS) are defined in details by the ISO 19111 classes in GeoAPI `referencing` packages.
But the ISO 19115 metadata standards do not reference those CRS classes directly (except in one case).
Instead the metadata standards reference CRS by their identifier (for example an EPSG code),
optionally accompanied by a code telling whether the CRS type is geographic, projected, temporal, a compound of the above, _etc_.
The ISO 19115 standard combines those two information in a `MD_ReferenceSystem` class.
The following table lists the associations to referencing systems as defined by the metadata standards:

.Associations to a Reference Systems defined by ISO 19115
[.compact, options="header"]
|==========================================================================================
|ISO 19115 Class     |Association to `MD_ReferenceSystem` |Association to an ISO 19111 type
|`MD_Metadata`       |`referenceSystemInfo`               |
|`LI_Source`         |`sourceReferenceSystem`             |
|`EX_VerticalExtent` |`verticalCRSId`                     |`verticalCRS`
|`MI_GCPCollection`  |`coordinateReferenceSystem`         |
|==========================================================================================

In order to have a more uniform way to handle reference systems,
GeoAPI replaces (_identifier_, _type code_) tuples by associations to the actual _Reference System_ objects.
GeoAPI does that by omitting the `MD_ReferenceSystem` and `MD_ReferenceSystemTypeCode` classes,
replacing them by associations to `RS_ReferenceSystem` instead as shown in the <<metadata-reference-system,reference system>> section.
The `RS_ReferenceSystem` class is a common parent for _Referencing by Coordinate_ (ISO 19111) and _Referencing by Geographic Identifier_ (ISO 19112).
The functionalities can by mapped as below:

.Mapping from ISO properties to GeoAPI replacements
[.compact, options="header"]
|=========================================================================================
|ISO 19115 class and property                   |GeoAPI replacement
|`MD_ReferenceSystem.referenceSystemIdentifier` |`RS_ReferenceSystem.identifier`
|`MD_ReferenceSystem.referenceSystemType`       |Type of the `RS_ReferenceSystem` instance
|=========================================================================================

As a side-effect of this replacement, `verticalCRSId` becomes redundant with `verticalCRS`.
Consequently the former is omitted from GeoAPI interfaces.
