[[metadata]]
=== Metadata packages

The GeoAPI metadata packages use the `org.opengis.metadata` namespace and implement the types defined
in the ISO 19115-1:2014 – _Metadata part 1: Fundamentals_ specification along with the modifications
of Amendments 1 and 2 from 2018 and 2020. They are completed or merged with the types defined in
ISO 19115-2:2019 – _Metadata part 2: Extensions for acquisition and processing_ specification.

The metadata packages of GeoAPI provide container types for descriptive elements which may be related to data sets or components.
All of these data structures are essentially containers for strings, dates or numbers,
and the interfaces consist almost exclusively of methods which provide read access to those types or a container.
The API defines no methods which manipulate or modify the data structures.
Implementers are free to provide a fully mutable implementation of GeoAPI interfaces,
but users may need to cast to the implementation classes in order to modify a metadata.

There is almost 500 properties in more than 150 metadata interfaces. This specification does not describe them;
see ISO 19115 together with GeoAPI <<conformance,Javadoc or Python-doc>> for a description of each property.
Implementers can support a subset of their choice.
The following UML example shows a few frequently used interfaces with some of their properties.
An <<metadata-java,example in annex>> show how to extract the individual name from a `Citation`.

.Example of a few metadata interfaces with a subset of their properties
image::metadata.svg[Partial UML for a few metadata types]


include::mapping.adoc[]

include::referencing.adoc[]

include::null-values.adoc[]

include::departures.adoc[]
