[[metadata]]
=== Metadata packages

The GeoAPI metadata packages use the `org.opengis.metadata` namespace
and implement the types defined in the specification from the International Organization for Standardization
ISO 19115-1:2014 – _Metadata part 1: fundamentals_ along with the modifications of Technical Corrigendum 1 from 2016 [red yellow-background]#(TODO: verify)#.
They are completed or merged with the types defined in ISO 19115-2:2009 – _Extensions for imagery and gridded data_ [red yellow-background]#(TODO: verify)#.

The metadata packages of GeoAPI provide container types for descriptive elements which may be related to data sets or components.
All of these data structures are essentially containers for strings, dates or numbers,
and the interfaces consist almost exclusively of methods which provide access to those types or a container.
The API defines no methods which manipulate or modify the data structures.

.Write access to metadata in Java
****
The metadata packages of GeoAPI have been built primarily in support of the geodetic types
defined in the referencing packages and therefore consider primarily read access to the data structure contents.
The GeoAPI metadata interfaces provide no methods to set the values of the types.
Furthermore, because the way that wildcards for Java Generics have been used in the interfaces,
the collection instances are constrained to be read only.
Implementors are free to provide a fully mutable implementation of GeoAPI interfaces,
but users may need to cast to the implementation classes in order to modify a metadata.
****

The GeoAPI rules of method return values have been relaxed for the metadata packages.
Elsewhere in GeoAPI, methods which have a mandatory obligation in the specification
must return an instance of the return type and cannot return the Java `null` or Python `None` reference.
However, in the metadata package this rule is relaxed because data sets are encountered so frequently
which have not correctly followed the requirements of the specification.
In the GeoAPI metadata packages, methods for mandatory properties should return a valid instance,
but users should be prepared to receive `null` (Java), `None` (Python) or an empty collection.
This modification has been adopted to allow implementations sufficient latitude
to handle metadata records which do not correctly conform to the specification.
Nonetheless, sophisticated implementations can determine if a metadata record conforms with the specification
by <<UML-introspection,inspecting the annotations at runtime>>.


include::mapping.adoc[]

include::referencing.adoc[]

include::usage.adoc[]

include::departures.adoc[]
