[[metadata-reference-system]]
==== Reference systems

Coordinate Reference Systems (CRS) are defined in details by the ISO 19111 interfaces in GeoAPI `referencing` packages.
A Reference System may also use geographic identifiers (ISO 19112) instead of coordinates.
The common parent interface of _Coordinate Reference System_ and _Reference System by Geographic Identifier_ is `ReferenceSystem`.
GeoAPI inserts this interface between `IdentifiedObject` and `CoordinateReferenceSystem` in ISO 19111 interface hierarchy
(this is a <<metadata-departures,departure from ISO standards>>). Usages are shown below:

.Associations from a metadata object to a reference system
[.compact, options="header"]
|==================================================================
|Metadata interface |Property name               |Property type
|`Metadata`         |`referenceSystemInfo`       |`ReferenceSystem`
|`Source`           |`sourceReferenceSystem`     |`ReferenceSystem`
|`VerticalExtent`   |`verticalCRS`               |`VerticalCRS`
|`GCPCollection`    |`coordinateReferenceSystem` |`ReferenceSystem`
|==================================================================

[red yellow-background]#TODO: replace above table by UML diagram showing `IdentifiedObject` and `ReferenceSystem`.#

The reference system identifier can be obtained by `ReferenceSystem.identifier`.
The reference system type (geographic, projected, compound, _etc._) can be determined
using language-specific instructions, for example `instanceof` in Java.
If a metadata instance does not have the full reference system definition but only its identifier,
then the implementation can use a custom `ReferenceSystem` instance.
