[[metadata-reference-system]]
==== Reference systems
[.reference]_Derived from ISO 19115-1:2014 §6.5.8_

The way GeoAPI handles reference systems in metadata differs significantly from ISO 19115.
Coordinate Reference Systems (CRS) are defined in details by the ISO 19111 standard.
But the ISO 19115 metadata standards do not reference those CRS interfaces directly
(except in one case), at the cost of some overlaps.
By contrast GeoAPI does not enforce such separation between standards when a bidirectional dependency can bring harmonization.
A bidirectional dependency does not imply that implementers have to support both ISO standards.

Coordinate Reference Systems (CRS) interfaces are provided in GeoAPI `referencing` packages.
A Reference System may also use geographic identifiers (ISO 19112) instead of coordinates.
GeoAPI supports both cases by defining `ReferenceSystem` as the common parent of
_Coordinate Reference System_ and _Reference System using Geographic Identifier_.
This is done by inserting the ISO 19115 `ReferenceSystem` interface between
`IdentifiedObject` and `CoordinateReferenceSystem` in ISO 19111 type hierarchy as shown below
(note: this diagram does not show all types, properties and associations for brevity reasons):

.Location of `ReferenceSystem` in the hierarchy of ISO 19111 types
image::metadata-referencing.svg[Partial UML of ReferenceSystem]

The following table lists all association to a reference system from the metadata packages:

.Associations from a metadata object to a reference system
[.compact, options="header"]
|==================================================================
|Metadata interface |Property name               |Property type
|`Metadata`         |`referenceSystemInfo`       |`ReferenceSystem`
|`Source`           |`sourceReferenceSystem`     |`ReferenceSystem`
|`VerticalExtent`   |`verticalCRS`               |`VerticalCRS`
|`GCPCollection`    |`coordinateReferenceSystem` |`ReferenceSystem`
|==================================================================
