[[geometry]]
=== Geometry packages

The GeoAPI geometry packages use the `opengis.geometry` namespace
and are placeholder for types defined in the ISO 19107:2003 - _Spatial schema_ specification.
[red yellow-background]#TODO: upgrade to ISO 19107:2019.#
The geometry specification provides a vector based spatial representation of elements.
The geometry types defined in GeoAPI include only the two simplest types from ISO specification
along with their abstract parent interfaces.
Those types are defined because they are needed by the referencing package.
Other types are expected to be added in future GeoAPI versions.

.Mapping of types from the geometry package
[.compact, options="header"]
|============================================================================
|ISO 19107 interface |Java type                                  |Python type
|`GM_Position`       |`org.opengis.geometry.coordinate.Position` |
|`DirectPosition`    |`org.opengis.geometry.DirectPostion`       |
|`GM_Envelope`       |`org.opengis.geometry.Envelope`            |
|============================================================================

The `DirectPosition` type represents a single location in the coordinate space defined by a `Coordinate​Reference​System`.
The `Envelope` type represents the lower and upper extreme values along each axis.
This type is frequently conflated with a bounding rectilinear box but the two types differ conceptually.
The `Envelope` type in ISO 19107 provides methods to obtain the "corners" of the envelope as `DirectPosition` instances.
However, users should note that these positions might not have any meaning in physical space.
For example the corners could be outside the Coordinate Reference System (CRS) domain of validity
even if the feature itself is fully inside that domain.
The corner `DirectPosition` instances are acting, for convenience,
as data containers for tuples of coordinates but not as representations of an actual position.

==== Geometry base class
Each geometric object is considered an infinite set of points (except the `Point` object which contains only itself).
As a set, their most fundamental operations are of the same nature as the standard operations of Java collections.
We could therefore see a geometry as a kind of `java.util.Set` in which the elements are points,
except that the number of elements contained in the set is infinite (with the exception of geometries representing a simple point).
To better represent this concept, the ISO standard and GeoAPI define a `TransfiniteSet` interface
which we could see as a `Set` of potentially infinite size.
Although a parent relationship exists conceptually between these interfaces,
GeoAPI does not define `TransfiniteSet` as a sub-interface of `java.util.Set`,
as the definition of certain methods such as `size()` and `iterator()` would be problematic.
However, we find very similar methods such as `contains(…)` and `intersects(…)`.

ISO 19107 defines two types of structures to represent a point: `GM_Point` and `DirectPosition`.
The first type is a true geometry and may therefore be relatively cumbersome, depending on the implementation.
The second type is not formally considered to be a geometry; it extends neither `GM_Object` nor `TransfiniteSet`.
It barely defines any operations besides the storing of a sequence of numbers representing a coordinate.
It may therefore be a more lightweight object.
In order to allow API to work equally with these two types of positions,
ISO 19107 defines `Position` as a union of `DirectPosition` and `GM_Point`.
GeoAPI represents the union as parent interface for compatibility with languages that do not support union.

include::departures.adoc[]
