/*
 *    GeoAPI - Java interfaces for OGC/ISO standards
 *    http://www.geoapi.org
 *
 *    This file is hereby placed into the Public Domain.
 *    This means anyone is free to do whatever they wish with this file.
 */
package org.opengis.openoffice;

import com.sun.star.uno.XInterface;
import com.sun.star.beans.XPropertySet;


/**
 * Services from the {@link org.opengis.referencing} package to be exported to
 * <a href="http://www.openoffice.org">OpenOffice.org</a>.
 *
 * This interface is derived from the {@code XReferencing.idl} file using the {@code javamaker}
 * tool provided in OpenOffice SDK, and disassembling the output using the {@code javap} tool
 * provided in Java SDK. This source file exists mostly for javadoc purpose and in order to keep
 * IDE happy. The {@code .class} file compiled from this source file <strong>must</strong> be
 * overwritten by the {@code .class} file generated by {@code javamaker}.
 *
 * @author  Martin Desruisseaux (IRD)
 * @version 3.1
 * @since   3.1
 */
public interface XReferencing extends XInterface {
    /**
     * Returns the identified object description from an authority code.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @return the identified object description, or {@code null}.
     */
    String getDescription(XPropertySet xOptions, String authorityCode);

    /**
     * Returns the scope for an identified object.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @return the identified object scope, or {@code null}.
     */
    String getScope(XPropertySet xOptions, String authorityCode);

    /**
     * Returns the valid area as a textual description for an identified object.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @return the identified object valid area, or {@code null}.
     */
    String getValidArea(XPropertySet xOptions, String authorityCode);

    /**
     * Returns the valid area as a geographic bounding box for an identified object. This method
     * returns a 2×2 matrix. The first row contains the latitude and longitude of upper left
     * corder, and the second row contains the latitude and longitude or bottom right corner. Units
     * are degrees.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @return the identified object bounding box, or {@code null}.
     */
    double[][] getBoundingBox(XPropertySet xOptions, String authorityCode);

    /**
     * Returns the remarks for an identified object.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @return the identified object remarks, or {@code null}.
     */
    String getRemarks(XPropertySet xOptions, String authorityCode);

    /**
     * Returns the axis name for the specified dimension in an identified object.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @param  dimension      the dimension (1, 2, ...).
     * @return the name of the given axis, or {@code null}.
     */
    String getAxis(XPropertySet xOptions, String authorityCode, int dimension);

    /**
     * Returns the value for a coordinate reference system parameter.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @param  parameter      the parameter name (e.g. "False easting").
     * @return the value of the given parameter, or {@code null}.
     */
    Object getParameter(XPropertySet xOptions, String authorityCode, String parameter);

    /**
     * Returns the Well Know Text (WKT) for an identified object.
     *
     * @param  xOptions       provided by OpenOffice.
     * @param  authorityCode  the code allocated by the authority.
     * @param  authority      the authority name for choice of parameter names. Usually "OGC".
     * @return the identified object WKT, or {@code null}.
     */
    String getWKT(XPropertySet xOptions, String authorityCode, Object authority);

    /**
     * Returns the Well Know Text (WKT) of a transformation between two coordinate reference
     * systems.
     *
     * @param  xOptions   provided by OpenOffice.
     * @param  sourceCRS  the authority code for the source coordinate reference system.
     * @param  targetCRS  the authority code for the target coordinate reference system.
     * @param  authority  the authority name for choice of parameter names. Usually "OGC".
     * @return the transform WKT, or {@code null}.
     */
    String getTransformWKT(XPropertySet xOptions, String sourceCRS, String targetCRS, Object authority);

    /**
     * Returns the accuracy of a transformation between two coordinate reference systems.
     *
     * @param  xOptions   provided by OpenOffice.
     * @param  sourceCRS  the authority code for the source coordinate reference system.
     * @param  targetCRS  the authority code for the target coordinate reference system.
     * @return the transformation accuracy, or {@code null}.
     */
    double getAccuracy(XPropertySet xOptions, String sourceCRS, String targetCRS);

    /**
     * Transforms coordinates from the specified source CRS to the specified target CRS.
     *
     * @param  xOptions     provided by OpenOffice.
     * @param  coordinates  the coordinates to transform.
     * @param  sourceCRS    the authority code for the source coordinate reference system.
     * @param  targetCRS    the authority code for the target coordinate reference system.
     * @return the transformed coordinates.
     */
    double[][] getTransformedCoordinates(XPropertySet xOptions, double[][] coordinates,
                                         String sourceCRS, String targetCRS);
}
