/*
 * $ Id $
 * $ Source $
 * Created on Jan 10, 2005
 */
package org.opengis.go.display.primitive.store;

import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.util.Map;

import org.opengis.util.InternationalString;

/**
 * The <code>GraphicStoreFactory</code> class/interface...
 * 
 * @author SYS Technologies
 * @author crossley
 * @version $Revision $
 */
public interface GraphicStoreFactory {

    /**
     * Ask for a GraphicStore connecting to the indicated provider or service.
     * The returned GraphicStore may have been previously cached.
     * <p>
     * Additional hints or configuration information may be provided according
     * to the metadata indicated by getParametersInfo. This information often includes
     * security information such as username and password.
     * </p>
     * 
     * @param provider Often a URL or JDBC URL locating the serivce to connect to
     * @param params Map of hints or configuration information.
     * @return GraphicStore connected to the indicated provider or service
     * @throws IOException if the GraphicStore cannot connect to its source
     */
    GraphicStore createGraphicStore(URI provider, Map params) throws IOException;

    /**
     * Ask for a new GraphicStore connecting to the indicated provider or service.
     * <p>
     * Additional hints or configuration information may be provided according
     * to the metadata indicated by getParametersInfo. This information often includes
     * security information such as username and password.
     * </p>
     * 
     * @param provider Often a URL or JDBC URL locating the serivce to connect to
     * @param params Map of hints or configuration information.
     * @return GraphicStore Datastore connected to the newly created provider or serivce.
     * @throws IOException
     */GraphicStore createNewGraphicStore(URI provider, Map params) throws IOException;

    /**
     * Icon representing this category of <code>GraphicStore</code>s.
     * <p>
     * Assumed to point to a 16x16 icon?
     * </p>
     * 
     * @return the icon.
     */
    URL getIcon();

    /**
     *  Display name used to communicate this type of GraphicStore to end users.
     * @return
     */
    InternationalString getDisplayName();

    /** 
     * Descrption of this type of GraphicStore.
     * @return
     */
    InternationalString getDescription();

    /**
     * Gets an <code>Object</code> array relating to the parameters needed (beyond
     * the URI) to instantiate a <code>FeatureStore</code>.  Should be replaced
     * with a <code>Param</code>[] based on ISO standards.
     * @return
     */
    Object[] getParametersInfo();

    /**
     * Indicates this GraphicStoreFactory communicate with the indicated provider or service.
     * <p>
     * This method should not fail, if a connection needs to be made
     * to parse a GetCapabilities file or negotiate WMS versions any
     * IO problems simply indicate the inabiity to process.
     * </p>
     * <p>
     * This method may be considered the same as: canProcess( provider, hints )
     * where hints was generated by using all the default values specified by the
     * getParameterInfo method.
     * </p>
     * @param provider Provider or Server of spatial information. 
     */
    boolean canProcess(URI provider);
    
    /**
     * Indicates this GraphicStoreFactory communicate with the indicated provider or service.
     * <p>
     * This method differs from canProcess in that additional configuration
     * information may be supplied. 
     * </p>
     * @param provider
     * @param params
     * @return <code>true</code> if this factory can communicate with the provider.
     */
    boolean canProcess(URI provider, Map params);

    /**
     * Allows a GraphicStoreFactory to ensure all its preconditions are met,
     * such as the presense of required libraries.
     * @return true if available
     */
    boolean isAvailable();

}