[[metadata_departures]]
==== Departures from ISO 19115

Metadata in GeoAPI differ from the OGC/ISO standards
as described in the following sub-sections.


[[metadata_departures_for_harmonization_with_19115_2]]
===== Harmonization with ISO 19115-2
A departure in the GeoAPI metadata packages from the published ISO 19115 standard is in the way GeoAPI metadata package
added the types and properties defined in the specification <<ISO19115-2>> – _Extensions for acquisition and processing_.
The latter was forced to create a number of interfaces to hold elements which naturally could occur directly in the interfaces defined by ISO 19115-1.
We integrated such interfaces directly into the existing interfaces rather than adding complexity to the API which exists by historical accident.
For example, ISO 19115-2 defines a `MI​_Band` interface which extends the `MD​_Band` interface defined by ISO 19115-1,
with the addition of a `transfer­Function­Type` property (among others) for completing the `scale­Factor` and
`offset` properties defined by ISO 19115-1. GeoAPI merges the two interfaces together,
with annotations (<<annotations>>) on each property for declaring the originating standard.
The metadata interfaces merged in such a way are:

.Metadata ISO 19115-2 interfaces merged with ISO 19115-1 parent interfaces
[options="header"]
|=====================================================================
|ISO 19115-1 parent interface |ISO 19115-2 subclass merged with parent
|`LI_ProcessStep`             |`LE_ProcessStep`
|`LI_Source`                  |`LE_Source`
|`MD_Band`                    |`MI_Band`
|`MD_CoverageDescription`     |`MI_CoverageDescription`
|`MD_Georectified`            |`MI_Georectified`
|`MD_Georeferenceable`        |`MI_Georeferenceable`
|`MD_ImageDescription`        |`MI_ImageDescription`
|`MD_Metadata`                |`MI_Metadata`
|=====================================================================


[[metadata_departures_for_harmonization_with_19111]]
===== Harmonization with ISO 19111
Coordinate Reference Systems (CRS) are defined in detail by the <<ISO19111>> standard.
But the ISO 19115 metadata standards do not reference the CRS interfaces directly (except `VerticalCRS`).
Instead, the metadata standards reference the CRS indirectly via a `MD_Reference­System` interface which contains the following properties.
At least one of the two first properties must be specified:

* `reference­System­Identifier` as, for example, an EPSG code.
* `crs` as an association to the full ISO 19111 CRS object.
* `coordinate­Epoch` as a mandatory property if the CRS is dynamic.
* `reference­System­Type` as an optional code telling whether the CRS type is geographic,
   projected, temporal, a compound of the above, a geographic identifier, _etc_.

In order to have a more uniform way to handle reference systems,
GeoAPI replaces the above (_identifier_, _crs_, _epoch_, _type_) tuple by a direct association to an ISO 19111 object.
The ISO 19115 `Reference­System` type is redefined as a subtype of ISO 19111 `Identified­Object` (<<reference_system_UML>>).
This type hierarchy replaces the `crs` property.
The `reference­System­Identifier` property defined by ISO 19115 is replaced by inheritance of `identifier` property from `Identified­Object`.
The `reference­System­Type` property (geographic, projected, compound, geographic identifier, _etc._) is available in the GeoAPI interface,
with a default implementation that determines the value using language-specific instructions such as `instanceof` in Java.
The `coordinate­Epoch` property is currently not defined, but can easily be fetched from the datum.

In the same spirit as above replacement, `verticalCRSId` is omitted because it is redundant with the existence of `verticalCRS`.
