[[reference_system]]
==== Reference systems
_Derived from <<ISO19115-1>> §6.5.8_

The way GeoAPI handles reference systems in metadata differs significantly from ISO 19115.
Coordinate Reference Systems (CRS) are defined in detail by the ISO 19111 standard.
But the ISO 19115 metadata standards do not reference the CRS interfaces directly
(except in one case), at the cost of some overlaps.
In contrast, GeoAPI does not enforce such separation between standards when a bidirectional dependency can bring harmonization.
A bidirectional dependency does not imply that implementers have to support both ISO standards.

Reference Systems interfaces are defined in GeoAPI `referencing` packages.
A Reference System may be a Coordinate Reference System (<<ISO19111>>)
or may use geographic identifiers (<<ISO19112>>).
GeoAPI supports both cases by defining `Reference­System` as the common parent of
_Coordinate Reference System_ and _Reference System using Geographic Identifier_.
This is done by inserting the ISO 19115 `Reference­System` interface between
`IdentifiedObject` and `CoordinateReferenceSystem` in ISO 19111 type hierarchy as shown below
(note: this diagram does not show all types, properties and associations for brevity reasons):

[[reference_system_UML]]
.Location of `ReferenceSystem` in the hierarchy of ISO 19111 types
image::metadata_referencing.svg[Partial UML of ReferenceSystem]

More information about the `Coordinate­Reference­System` interface is given
in the _Referencing packages_ section (<<referencing>>).
The following table lists all association to a reference system from the metadata packages:

.Associations from a metadata object to a reference system
[options="header"]
|==================================================================
|Metadata interface |Property name               |Property type
|`Metadata`         |`referenceSystemInfo`       |`ReferenceSystem`
|`Source`           |`sourceReferenceSystem`     |`ReferenceSystem`
|`VerticalExtent`   |`verticalCRS`               |`VerticalCRS`
|`GCPCollection`    |`coordinateReferenceSystem` |`ReferenceSystem`
|==================================================================
