[[UML_introspection]]
==== UML at runtime

The annotations in API (<<annotations>>) are available at runtime by introspection.
This is useful, for example, when code needs to marshall data using the names
defined by the ISO standard rather than the GeoAPI names.
In the following example, the top-level annotations indicate that the `ProjectedCRS` interface
was derived from a type also named `ProjectedCRS` in the ISO 19111 standard.
The enclosed annotation indicates that the `getCoordinate­System()` method
was derived from a property named `coordinate­System` in the ISO 19111 standard,
and that a non-null value must be provided by every `ProjectedCRS` instance:


[source,java]
------------------------------------------------------------
@Classifier(Stereotype.TYPE)
@UML(identifier = "ProjectedCRS", specification = ISO_19111)
public interface ProjectedCRS extends DerivedCRS {
    /**
     * Returns the coordinate system.
     */
    @UML(identifier    = "coordinateSystem",
         obligation    = MANDATORY,
         specification = ISO_19111)
    CartesianCS getCoordinateSystem();
}
------------------------------------------------------------

At runtime, the annotation of a reference to a GeoAPI interface can be obtained as follows,
taking as an example the method `getCoordinate­System()` in the `ProjectedCRS` interface:

[source,java]
---------------------------------------------------------------------------------------
Class<?>      type          = ProjectedCRS.class;
Method        method        = type.getMethod("getCoordinateSystem");
UML           annotation    = method.getAnnotation(UML.class);
String        identifier    = annotation.identifier().get();    // = "coordinateSystem"
Specification specification = annotation.specification();       // = ISO 19111
Obligation    obligation    = annotation.obligation();          // = mandatory
---------------------------------------------------------------------------------------

Java provides a class instance like the `ProjectedCRS​.class` instance used here for every type, either interface or class, defined in the runtime.
The `getMethod(…)` call uses introspection to obtain a reference to the method from which the annotation can then be obtained.
The annotation system therefore provides access, at runtime, to the original definition of the element.
