[[java_code_list]]
==== Code list at runtime

Controlled vocabularies (<<controlled_vocabulary>>) can take the form of enumerations or code lists.
These two types are implemented by `java​.lang​.Enum` and `org​.opengis​.util​.Code­List` respectively.
The use of `Code­List` classes includes accessing statically defined elements,
defining new elements and retrieving any element defined for the code list.
Considering, for example, `org​.opengis​.referencing​.cs​.Axis­Direction`,
the following codes could be used:

[source,java]
---------------------------------------------------------------------------------------------
AxisDirection north;
north = AxisDirection.NORTH;                                // Compile-time value (safest).
north = AxisDirection.valueOf("NORTH");                     // Runtime value (more dynamic).
north = CodeList.valueOf(AxisDirection.class, "NORTH");     // Runtime type and value.
---------------------------------------------------------------------------------------------

where the `.valueOf(…)` form above will create a new value if it does not exist.
Special care should be taken to keep such calls consistent throughout the code
since the `Code­List` will create a new element if there are any difference in the `String` parameters.
The list of all elements (including new elements created by `valueOf(…)`) can be obtained as below:

[source,java]
--------------------------------------------------
AxisDirection[] elements = AxisDirection.values();
--------------------------------------------------
