[[java_coordinate_operation]]
==== Coordinate operation

This usage examples lets implementations infer a coordinate operation (<<coordinate_operation>>)
for a pair of coordinate reference systems.
The `Coordinate­Operation­Factory` does all the work of establishing
which parameters should be used and correctly instantiating the operation.

[source,java]
---------------------------------------------------------------------------
// We assume these instances are already available.
CoordinateReferenceSystem sourceCRS = ...;
CoordinateReferenceSystem targetCRS = ...;

// Implementation infers an operation.
CoordinateOperationFactory opFactory = ...;
CoordinateOperation op = opFactory.createOperation(sourceCRS, targetCRS);
---------------------------------------------------------------------------

The following example uses the operation we just created for transforming coordinate tuples.
It is possible to transform `Direct­Position` instances, but if there are many points to transform
then packing them in a single array is generally more efficient.
For simplicity reasons, this example performs the coordinate operation in-place
(i.e. transformed coordinates overwrite source coordinates)
and assumes that both source and target CRS are two-dimensional.
But GeoAPI is not restricted to these assumptions.

[source,java]
---------------------------------------------------------------------------------
// We assume this instance is already available.
CoordinateOperation op = ...;

// We assume that the source CRS is geographic.
double[] coordinates = {
    49.250, -123.100,           // Vancouver
    37.783, -122.417,           // San-Francisco
    45.500,  -73.567,           // Montreal
    40.713,  -74.006,           // New-York
    48.801,    2.351,           // Paris
    35.666,  139.772};          // Tokyo

MathTransform mt = op.getMathTransform();
mt.transform(coordinates, 0, coordinates, 0, 6);    // 6 is the number of points.
---------------------------------------------------------------------------------
