[[naming]]
=== Name types

A name is a sequence of identifiers rooted within the context of a namespace.
`NameSpace` defines a domain in which "names" given by character strings can be mapped to objects.
For example a class forms a namespace for the properties that the class contains.
While ISO 19103 defines mapping functions from a name to the object identified by that name,
these mapping functions are not part of the `NameSpace` interface defined by GeoAPI.
These mappings are left to other frameworks (for example _Java Naming and Directory Interface_).


.Name types mapping
[options="header"]
|===========================================================
|ISO 19103 type |Java type                      |Python type
|(constructors) |`org.opengis.util.NameFactory` |
|`NameSpace`    |`org.opengis.util.NameSpace`   |
|`GenericName`  |`org.opengis.util.GenericName` |
|`ScopedName`   |`org.opengis.util.ScopedName`  |
|`LocalName`    |`org.opengis.util.LocalName`   |
|`TypeName`     |`org.opengis.util.TypeName`    |
|`MemberName`   |`org.opengis.util.MemberName`  |
|===========================================================

`GenericName` is the base type for all names in a `NameSpace`.
A generic name can be either a `LocalName`, or a `ScopedName` which is a composite of
a `LocalName` for locating another `NameSpace` and a `GenericName` valid in that name space.
`TypeName` and `MemberName` names are subtypes of `LocalName`
for referencing a type (for example a class) and a member (for example a property in a class) respectively.
The `NameFactory` is an extension of the GeoAPI project designed to allow the construction of instances of these name types.

.Mapping to Java Naming and Directory Interface™ (JNDI)
****
The mapping functions defined by ISO 19103 are not part of the `NameSpace` interface defined by GeoAPI.
Java applications which need such mapping may use the methods in the `javax.naming.Context` interface instead:

.Java Naming and Directory Interface equivalences
[options="header"]
|====================================================================================
|ISO 19103 `NameSpace` member   |`org.opengis.util.NameSpace` |`javax.naming.Context`
|`isGlobal`                     |`isGlobal()`                 |
|`acceptableClassList`          |                             |
|`generateID(Any*)`             |                             |
|`locate(LocalName)`            |                             |`lookup(Name)`
|`name`                         |`name()`                     |`getNameInNamespace()`
|`registerID(LocalName, Any)`   |                             |`bind​(Name, Object)`
|`select(GenericName)`          |                             |`lookup(Name)`
|`unregisterID(LocalName, Any)` |                             |`unbind​(Name)`
|====================================================================================
****
