[[core-types]]
== Core data types mapping

The ISO 19103 specification (_Geographic Information – Conceptual schema language_) defines types
which are used as building blocks by the other standards in the 19100 series.
ISO 19103:2015 defines Primitive types (§7.2 of that standard), Collection types (§7.3), Enumerated types (§7.4),
Name types (§7.5), Record types (§7.7) and Unit of Measure types (§C.4).
GeoAPI maps these types either to existing types from the {supported-languages} standard libraries or, when needed,
to types defined in the `org.opengis.util` package.
That utility package is used by GeoAPI for types defined in the ISO 19103 specification
for which no equivalence is already present in the {supported-languages} standard libraries.

For various practical reasons the mapping from ISO types to programming language types is not a one-to-one relationship.
The mapping actually used is explained below.
Furthermore not all of the types in ISO 19103 have a mapping defined because the need for these types has not yet appeared,
since they have not yet appeared in any other specification for which GeoAPI defines interfaces.
Such types are listed as "unimplemented" in the tables below.


[[primitives]]
=== Primitive types

Each primitive type of the ISO/OGC specifications maps to zero, one or two object structures in GeoAPI.
Where the mapping can be made directly to a programming language primitive type, such as `int` and `double`,
the language primitive is preferred. However, when the value must be able to be set to `null`,
the object wrapper of that primitive may be used in languages where "primitives" and "wrappers" are distinct.
The following table shows the mapping used by GeoAPI to represent the primitive types in the ISO 19100 series.

.Primitive types mapping
[options="header"]
|================================================================
|ISO 19103 type        |Java type                    |Python type
|`Boolean`             |`java.lang.Boolean` ^(1)^    |
|`Number`              |`java.lang.Number`           |
|`Integer`             |`java.lang.Integer` ^(1)(2)^ |
|`Real`                |`java.lang.Double`  ^(1)^    |
|`Decimal` ^(3)^       |`java.math.BigDecimal`       |
|`Vector`              |unimplemented                |
|`CharacterString`     |`java.lang.String`  ^(4)^    |
|`Sequence<Character>` |`java.lang.CharSequence`     |
|`CharacterSetCode`    |`java.nio.charset.Charset`   |
|`Date`                |`java.util.Date`             |
|`Time`                |`java.util.Date`             |
|`DateTime`            |`java.util.Date`             |
|================================================================

[small]#(1) The primitive type, such as `int` and `double`, is used instead of the wrapper where the value can not be `null`.# +
[small]#(2) Sometime substituted by `java.lang.Long` or `long` where the value may exceed 2^32^.# +
[small]#(3) `Decimal` differs from `Real`, as `Decimal` is exact in base 10 while `Real` may not.# +
[small]#(4) Substituted by `org.opengis.util.InternationalString` where the string representation depends on the locale.#

The interface `org.opengis.util.InternationalString` is an extension defined by GeoAPI to handle textual sequences
which may potentially need to be translated for users of different locales.
Conceptually this acts as a `CharacterString` but may, depending on the implementation,
provide access to locale specific representations of that string.
This is useful, for example, when an implementation is operating on a server that serves multiple languages simultaneously,
to allow sending string representations in the locale of the client rather than the locale of the server running the GeoAPI implementation.

[small]#Note: `InternationalString` is inspired by JSR-150 (Internationalization Service for J2EE) with support for different timezones omitted.#


[[collections]]
=== Collections

GeoAPI implements ISO 19103 collection types using the standard Collections Frameworks provided by {supported-languages}.
A `Set` is a finite collection of objects where each object appears only once.
A `Bag` is similar to a `Set` except that it may contain duplicated instances.
The order of elements in a `Set` or a `Bag` is not specified.
A `Sequence` is similar to a `Bag` except that elements are ordered.

.Collections mapping
[options="header"]
|===================================================
|ISO 19103 type |Java type              |Python type
|`Collection`   |`java.util.Collection` |
|`Bag`          |`java.util.Collection` |
|`Set`          |`java.util.Set`        |
|`Sequence`     |`java.util.List`       |
|`Dictionary`   |`java.util.Map`        |
|===================================================

Unless otherwise required by the semantic of a property, GeoAPI preferably uses the `Collection` type in method signatures.
The `Set` type is not the default type because enforcing element uniqueness may constraint implementations to use hash tables
or similar algorithms, which is not always practical.


[[enumerations]]
=== Enumerated types

GeoAPI distinguishes between two enumerated types depending on whether the complete set of literal types is known
when the code is originally created, or if the list may be extended at run time.
Many language provides an `enum` construct for the former case and GeoAPI defines the `CodeList` abstract class for the later case.

.Enumerated types mapping
[options="header"]
|========================================================
|ISO 19103 type |Java type                   |Python type
|CodeList       |`org.opengis.util.CodeList` |
|Enumeration    |`java.lang.Enum`            |
|`Bit`          |unimplemented               |
|`Digit`        |unimplemented               |
|`Sign`         |unimplemented               |
|========================================================


[[naming]]
=== Name types

A name is a sequence of identifiers rooted within the context of a namespace.
`NameSpace` defines a domain in which "names" given by character strings can be mapped to objects.
For example a class forms a namespace for the properties that the class contains.
While ISO 19103 defines mapping functions from a name to the object identified by that name,
these mapping functions are not part of the `NameSpace` interface defined by GeoAPI.
These mappings are left to other frameworks (for example _Java Naming and Directory Interface_).


.Name types mapping
[options="header"]
|===========================================================
|ISO 19103 type |Java type                      |Python type
|(constructors) |`org.opengis.util.NameFactory` |
|`NameSpace`    |`org.opengis.util.NameSpace`   |
|`GenericName`  |`org.opengis.util.GenericName` |
|`ScopedName`   |`org.opengis.util.ScopedName`  |
|`LocalName`    |`org.opengis.util.LocalName`   |
|`TypeName`     |`org.opengis.util.TypeName`    |
|`MemberName`   |`org.opengis.util.MemberName`  |
|===========================================================

`GenericName` is the base type for all names in a `NameSpace`.
A generic name can be either a `LocalName`, or a `ScopedName` which is a composite of
a `LocalName` for locating another `NameSpace` and a `GenericName` valid in that name space.
`TypeName` and `MemberName` names are subtypes of `LocalName`
for referencing a type (for example a class) and a member (for example a property in a class) respectively.
The `NameFactory` is an extension of the GeoAPI project designed to allow the construction of instances of these name types.

.Mapping to Java Naming and Directory Interface™ (JNDI)
****
The mapping functions defined by ISO 19103 are not part of the `NameSpace` interface defined by GeoAPI.
Java applications which need such mapping may use the methods in the `javax.naming.Context` interface instead:

.Java Naming and Directory Interface equivalences
[options="header"]
|====================================================================================
|ISO 19103 `NameSpace` member   |`org.opengis.util.NameSpace` |`javax.naming.Context`
|`isGlobal`                     |`isGlobal()`                 |
|`acceptableClassList`          |                             |
|`generateID(Any*)`             |                             |
|`locate(LocalName)`            |                             |`lookup(Name)`
|`name`                         |`name()`                     |`getNameInNamespace()`
|`registerID(LocalName, Any)`   |                             |`bind​(Name, Object)`
|`select(GenericName)`          |                             |`lookup(Name)`
|`unregisterID(LocalName, Any)` |                             |`unbind​(Name)`
|====================================================================================
****


[[records]]
=== Record types

Records define new data type as an heterogeneous aggregation of component data types.
Each data component is identified by a `MemberName` and has exactly one value per record.

.Record types mapping
[options="header"]
|=============================================================
|ISO 19103 type |Java type                        |Python type
|`Schema`       | Unimplemented                   |
|`Any`          | `java.lang.Object`              |
|`Type`         | `org.opengis.util.Type`         |
|`RecordSchema` | `org.opengis.util.RecordSchema` |
|`Record`       | `org.opengis.util.Record`       |
|`RecordType`   | `org.opengis.util.RecordType`   |
|`Field`        |                                 |
|`FieldType`    |                                 |
|=============================================================

NOTE: `Record` and `RecordType` have some similarities with `Feature` and `FeatureType` respectively
      but without multi-occurrence, associations, operations and type inheritance.
      If we push the comparison with features further,
      record `Field` and `FieldType` are similar to feature `Attribute` and `AttributeType` respectively.
